import type {
  BillingAgreement,
  DomainMigration,
  DomainRenewalCycle,
  ManagedDomain,
  Order,
  PaymentAttempt,
} from "../../src/payload-types"

const NOW = "2026-07-30T10:00:00.000Z"

export const validOrder = (overrides: Partial<Order> = {}): Order => ({
  id: 600,
  orderNumber: "SIAB-500-TEST",
  generationRun: 500,
  tenant: 1,
  state: "accepted",
  checkoutProfileKey: "run:500:checkout-profile:1",
  catalogVersion: "2026-07-26.1",
  contractingPartyProfileVersion: 1,
  termsVersion: "platform-terms-2026-07-07",
  privacyVersion: "privacy-2026-07-07",
  businessUseDeclarationVersion: "business-use-2026-07-07",
  acceptedAt: NOW,
  customerName: "Ada Lovelace",
  customerEmail: "client@example.com",
  companyName: "Acme Studio",
  billingAddress: { country: "NL" },
  packageCode: "siteinabox-monthly",
  billingPeriod: "monthly",
  renewalTerms: "Renews monthly until cancelled.",
  lineItems: [],
  currency: "EUR",
  subtotalNetMinor: 41_240,
  vatAmountMinor: 8_660,
  totalGrossMinor: 49_900,
  subtotalNet: 412.4,
  vatAmount: 86.6,
  totalGross: 499,
  domain: "example.nl",
  domainRegistrant: {
    name: "Ada Lovelace",
    email: "client@example.com",
    country: "NL",
  },
  legalDocuments: [10, 11],
  paymentStatus: "pending",
  paymentProvider: "mollie",
  createdAt: NOW,
  updatedAt: NOW,
  ...overrides,
})

export const validBillingAgreement = (
  overrides: Partial<BillingAgreement> = {},
): BillingAgreement => ({
  id: 900,
  idempotencyKey: "mollie:billing-agreement:order:600:v1",
  originatingOrder: 600,
  checkoutProfile: 800,
  tenant: 1,
  state: "mandate_pending",
  provider: "mollie",
  providerCustomerId: "cst_test_1",
  providerMandateId: null,
  catalogVersion: "2026-07-26.1",
  packageCode: "siteinabox-monthly",
  billingPeriod: "monthly",
  currency: "EUR",
  recurringNetAmountMinor: 1_900,
  renewalIntent: true,
  serviceSuspensionStatus: "none",
  reconciliationRequired: false,
  stateHistory: [],
  createdAt: NOW,
  updatedAt: NOW,
  ...overrides,
})

export const validPaymentAttempt = (
  overrides: Partial<PaymentAttempt> = {},
): PaymentAttempt => ({
  id: 901,
  idempotencyKey: "mollie:first-payment:order:600:v1",
  order: 600,
  billingAgreement: 900,
  tenant: 1,
  attemptNumber: 1,
  state: "created",
  purpose: "first_payment",
  sequenceType: "first",
  provider: "mollie",
  providerPaymentId: null,
  providerStatus: null,
  currency: "EUR",
  netAmountMinor: 41_240,
  vatAmountMinor: 8_660,
  grossAmountMinor: 49_900,
  reconciliationRequired: false,
  stateHistory: [],
  createdAt: NOW,
  updatedAt: NOW,
  ...overrides,
})

export const validManagedDomain = (
  overrides: Partial<ManagedDomain> = {},
): ManagedDomain => ({
  id: 950,
  domainNameAscii: "example.nl",
  tld: "nl",
  provisioningIdempotencyKey: "domain:order:600:example.nl",
  originatingOrder: 600,
  registrantProfile: 800,
  tenant: 1,
  state: "active",
  custodyStatus: "managed",
  initialOperation: "registration",
  registrantOwnership: "customer",
  provider: "openprovider",
  providerDomainId: "9001",
  providerCustomerHandle: "OWNER-CLIENT",
  providerRegistrationState: "confirmed",
  cloudflareZoneId: "zone-test-1",
  cloudflareNameservers: ["ada.ns.cloudflare.com", "bob.ns.cloudflare.com"],
  edgeRoutingStatus: "active",
  adminHttpsStatus: "verified",
  registrantVerificationStatus: "verified",
  authoritativeDnsStatus: "verified",
  httpsStatus: "verified",
  entitlementStatus: "active",
  customerStatus: "active",
  renewalIntent: true,
  registeredAt: NOW,
  providerRenewalDate: "2027-07-30T00:00:00.000Z",
  providerAutorenew: "on",
  transferOutCodeDeliveryStatus: "not_requested",
  transferOutProviderMissingCount: 0,
  reconciliationRequired: false,
  stateHistory: [],
  createdAt: NOW,
  updatedAt: NOW,
  ...overrides,
})

export const validDomainMigration = (
  overrides: Partial<DomainMigration> = {},
): DomainMigration => ({
  id: 960,
  idempotencyKey: "domain-migration:order:600:v1",
  originatingOrder: 600,
  checkoutProfile: 800,
  tenant: 1,
  managedDomain: validManagedDomain({
    state: "transfer_pending",
    initialOperation: "transfer",
    providerDomainId: null,
    providerCustomerHandle: null,
    providerRegistrationState: "not_started",
    cloudflareZoneId: null,
    cloudflareNameservers: null,
    edgeRoutingStatus: "pending",
    adminHttpsStatus: "pending",
    registrantVerificationStatus: "not_checked",
    authoritativeDnsStatus: "pending",
    httpsStatus: "pending",
    entitlementStatus: "pending",
    customerStatus: "provisioning",
    registeredAt: null,
    providerRenewalDate: null,
    providerAutorenew: "unknown",
  }),
  domainNameAscii: "example.nl",
  tld: "nl",
  acceptedClassification: "automatic",
  state: "ready_to_prepare",
  sourceMechanism: "cloudflare_api_v1",
  sourceZoneHash: "source-zone-hash",
  sourceZoneSnapshot: {
    domain: "example.nl",
    nameservers: ["ns1.source.example", "ns2.source.example"],
    records: [
      { type: "A", name: "example.nl", content: "192.0.2.10", ttl: 300 },
    ],
    dnssec: { enabled: false, parentDsRecords: [] },
    capturedAt: NOW,
  },
  targetZoneSnapshot: {
    domain: "example.nl",
    nameservers: ["ada.ns.cloudflare.com", "bob.ns.cloudflare.com"],
    records: [
      { type: "A", name: "example.nl", content: "192.0.2.10", ttl: 300 },
    ],
    dnssec: { enabled: false, parentDsRecords: [] },
    capturedAt: NOW,
  },
  rollbackEvidence: {
    sourceNameservers: ["ns1.source.example", "ns2.source.example"],
    sourceDnssec: { enabled: false, parentDsRecords: [] },
    sourceZoneHash: "source-zone-hash",
    capturedAt: NOW,
  },
  encryptedTransferCode: "opaque-encrypted-transfer-authority",
  encryptedSourceRefreshAuthority: "opaque-encrypted-source-authority",
  sourceRefreshAuthorityExpiresAt: "2026-08-30T10:00:00.000Z",
  sourceAuthorityLastVerifiedAt: NOW,
  operatorWorkAuthorizationState: "not_required",
  dnssecPhase: "source_unsigned",
  dnssecWriteState: "not_started",
  customerActions: [],
  providerTransferState: "not_started",
  cloudflareZoneState: "not_started",
  cutoverWriteState: "not_started",
  rollbackWriteState: "not_started",
  reconciliationRequired: false,
  stateHistory: [],
  createdAt: NOW,
  updatedAt: NOW,
  ...overrides,
})

export const validRenewalCycle = (
  overrides: Partial<DomainRenewalCycle> = {},
): DomainRenewalCycle => ({
  id: 970,
  idempotencyKey: "domain-renewal:managed-domain:950:2027-07-30",
  managedDomain: 950,
  billingAgreement: 900,
  tenant: 1,
  state: "scheduled",
  coverageStartsAt: "2027-07-30T00:00:00.000Z",
  coverageEndsAt: "2028-07-30T00:00:00.000Z",
  providerRenewalDate: "2027-07-30T00:00:00.000Z",
  providerSafeCutoffAt: "2027-07-23T00:00:00.000Z",
  renewalIntentSnapshot: true,
  providerRenewalMode: "provider_autorenew",
  providerAutorenew: "on",
  providerWriteState: "not_required",
  currency: "EUR",
  providerOperationPriceNetMinor: 1_000,
  includedAllowanceNetMinor: 1_000,
  surchargeNetMinor: 0,
  financialCoverageState: "included_allowance",
  pricingEvidence: {
    quotedAt: NOW,
    provider: "openprovider",
  },
  reconciliationRequired: false,
  stateHistory: [],
  createdAt: NOW,
  updatedAt: NOW,
  ...overrides,
})
