import { beforeEach, describe, expect, it, vi } from "vitest"
const seams = vi.hoisted(() => ({ read: vi.fn(), load: vi.fn(), record: vi.fn(), customizer: vi.fn() }))
vi.mock("next/headers", () => ({ headers: async () => new Headers({ host: "admin.siteinabox.nl", cookie: "signed" }) }))
vi.mock("next-intl/server", () => ({ getTranslations: async () => (key: string) => key }))
vi.mock("@/lib/auth/verifiedPreviewSession", () => ({ readVerifiedPreviewSession: seams.read }))
vi.mock("@/lib/preview/previewAccess", () => ({ loadPreviewGrantContext: seams.load, loadPreviewGrantAuthority: seams.load, normalizePreviewClientSlug: (value: string) => value }))
vi.mock("@/lib/preview/authenticatedPreviewActivity", () => ({ recordVerifiedPreviewActivity: seams.record }))
vi.mock("@/lib/preview/customizer", () => ({ getPreviewCustomizerDataForGrant: seams.customizer }))
vi.mock("@/components/renderer-frame/RendererFrameRuntime", () => ({ RendererFrameRuntime: () => null }))
vi.mock("@/components/preview/PreviewReview", () => ({ PreviewReview: () => null }))
vi.mock("@/lib/preview/previewHost", () => ({ isPreviewHost: async () => true }))
vi.mock("@/lib/preview/previewFixture", () => ({ isPreviewFixtureRoute: () => false }))
const source = { customerEmail: "verified@example.test", clientSlug: "fixture", payload: {}, tenant: {}, run: {}, pages: [], grant: {} }
beforeEach(() => { vi.clearAllMocks(); seams.read.mockResolvedValue({ session: { id: "signed-source" }, user: { id: "user", email: source.customerEmail, emailVerified: true } }); seams.load.mockResolvedValue(source); seams.record.mockResolvedValue(undefined); seams.customizer.mockResolvedValue({ currentPage: {}, settings: {}, rendererTheme: {}, tenant: { id: 1, slug: "fixture", domain: "fixture.test" } }) })
describe("authenticated direct checkout visits count as customer activity", () => {
  it("records only after verified session and grant authority", async () => {
    const { requirePreviewCheckoutContext } = await import("@/app/(frontend)/(site-preview)/[clientSlug]/checkout/previewCheckoutContext")
    expect(await requirePreviewCheckoutContext("fixture")).toBe(source)
    expect(seams.record).toHaveBeenCalledWith(expect.any(Headers), "fixture")
    expect(seams.load.mock.invocationCallOrder[0]).toBeLessThan(seams.record.mock.invocationCallOrder[0] ?? 0)
  })
  it("direct review and renderer-frame visits record after their grant/page access succeeds", async () => {
    const { default: review } = await import("@/app/(frontend)/(site-preview)/[clientSlug]/review/page")
    await review({ params: Promise.resolve({ clientSlug: "fixture" }) })
    expect(seams.record).toHaveBeenCalledWith(expect.any(Headers), "fixture")
    seams.record.mockClear()
    const { default: frame } = await import("@/app/(renderer-frame)/renderer-frame/preview/[clientSlug]/[[...pageSlug]]/page")
    await frame({ params: Promise.resolve({ clientSlug: "fixture" }) })
    expect(seams.record).toHaveBeenCalledWith(expect.any(Headers), "fixture")
    expect(seams.customizer.mock.invocationCallOrder[0]).toBeLessThan(seams.record.mock.invocationCallOrder[0] ?? 0)
    seams.record.mockClear()
    seams.customizer.mockRejectedValueOnce(new Error("Revoked page authority"))
    await expect(frame({ params: Promise.resolve({ clientSlug: "fixture" }) })).rejects.toThrow("Revoked page authority")
    expect(seams.record).not.toHaveBeenCalled()
  })
  it("forged or revoked visits never advance activity", async () => {
    const { requirePreviewCheckoutContext } = await import("@/app/(frontend)/(site-preview)/[clientSlug]/checkout/previewCheckoutContext")
    seams.read.mockResolvedValueOnce(null)
    await expect(requirePreviewCheckoutContext("fixture")).rejects.toThrow()
    expect(seams.record).not.toHaveBeenCalled()
    seams.load.mockRejectedValueOnce(new Error("Preview access is not available"))
    await expect(requirePreviewCheckoutContext("fixture")).rejects.toThrow()
    expect(seams.record).not.toHaveBeenCalled()
  })
})
