import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

import { builderAgentStatus } from "@/components/builder/builderPresence"
import {
  builderPreviewActions,
  defaultBuilderMessages,
  isBuilderAgentStage,
  messagesForBuilderSession,
  OPEN_PREVIEW_ACTION,
  withOpenPreviewAction,
} from "@/lib/builder/thread"

const read = (path: string) => readFileSync(path, "utf8")

describe("builder shell chrome", () => {
  const shell = read("src/components/builder/BuilderShell.tsx")
  const header = read("src/components/builder/BuilderAgentHeader.tsx")
  const stage = read("src/components/builder/BuilderAgentStage.tsx")
  const logo = read("src/components/builder/BuilderLogo.tsx")
  const thread = read("src/components/builder/BuilderThread.tsx")
  const composer = read("src/components/builder/BuilderComposer.tsx")
  const presence = read("src/components/builder/builderPresence.ts")
  const pager = read("src/components/builder/useBuilderMobilePager.ts")
  const css = read("src/styles/siab.css")
  const chrome = [shell, header, stage, logo, thread, composer, presence, css].join("\n")

  it("starts agent-first and only mounts the preview workspace after a slug exists", () => {
    expect(shell).toContain("data-builder-mode={hasPreview ? \"workspace\" : \"agent\"}")
    expect(shell).toContain("isBuilderAgentStage")
    expect(shell).toContain("withOpenPreviewAction")
    expect(shell).toContain("BuilderAgentStage")
    expect(shell).toContain("hasPreview ? pagerRef")
    expect(shell).not.toContain("nudgedPreview")
    expect(shell).not.toContain("Preview verschijnt hier")
    expect(shell).not.toContain("neoChrome")
    expect(stage).toContain("data-siab-builder-stage")
    expect(stage).toContain("BUILDER_STAGE_HEADLINE")
    expect(stage).toContain("BuilderLogo")
    expect(stage).not.toContain("BuilderThread")
    expect(stage).not.toContain("{children}")
    expect(stage).not.toContain("Card")
    expect(stage).not.toContain("BUILDER_STAGE_SUBHEAD")
    expect(shell).toContain("data-siab-builder-chat")
    expect(shell).toContain("BUILDER_LANDING_OPENER")
    expect(shell).toContain("requestAnimationFrame")
    expect(shell).toContain("prefers-reduced-motion")
    expect(shell).toContain("data-split-motion={hasPreview")
    expect(shell).not.toContain("BUILDER_CHAT_WELL_CLASS")
    expect(header).toContain("flex w-full shrink-0")
    expect(composer).toContain("flex w-full shrink-0")
    expect(shell).toContain("data-split-ready")
    expect(shell).not.toContain("lg:grid-cols-[28rem_minmax(0,1fr)]")
    expect(css).toContain("@property --siab-builder-chat-col")
    expect(css).toContain("@property --siab-builder-preview-col")
    expect(css).toContain("--siab-builder-chat-col: 28rem")
    expect(css).toContain("--siab-builder-preview-col: 1fr")
    expect(css).toContain("[data-siab-builder-chat]")
    expect(css).toContain("siab-builder-stage-spacer")
    expect(css).toContain("flex-grow")
    expect(css).toContain("grid-template-columns")
    expect(css).toContain("siab-builder-fade-in")
    expect(css).toContain("--siab-builder-motion")
    expect(css).toContain("prefers-reduced-motion: reduce")
    expect(shell.split("{composer}").length).toBe(2)
    expect(shell).not.toContain("framer-motion")
    expect(shell).not.toContain("view-transition")
    expect(stage).not.toContain("max-lg:has-[:focus-within]:justify-end")
    expect(composer).toContain("max-lg:border-t-2 max-lg:border-border max-lg:p-4")
    expect(composer).toContain("max-lg:min-h-20")
    expect(composer).toContain("placeholder={placeholder}")
    expect(composer).toContain("placeholder:text-muted-foreground/40")
    expect(composer).toContain("focus-visible:ring-0")
    expect(composer).not.toContain("has-[textarea:focus-visible]:ring-2")
    expect(composer).toContain("lg:hover:border-foreground")
    expect(composer).not.toContain("lg:hover:border-[3px]")
    expect(composer).not.toContain("lg:hover:outline-2")
    expect(composer).not.toContain("border-width")
    expect(composer).toContain("lg:has-[:focus-visible]:border-foreground")
    expect(composer).not.toContain("lg:has-[:focus-visible]:outline-2")
    expect(composer).not.toContain("lg:has-[:focus-visible]:border-[3px]")
    expect(shell).toContain("placeholder={agentStage ? BUILDER_STAGE_PLACEHOLDER : undefined}")
    expect(read("src/lib/builder/thread.ts")).toContain("Wat gaan we bouwen?")
    expect(read("src/lib/builder/thread.ts")).toContain("max-w-[40rem]")
    expect(read("src/lib/builder/thread.ts")).toContain("Ik ben kapper in Tilburg")
    expect(read("src/lib/builder/thread.ts")).not.toContain("Hoi.")
  })

  it("uses a Lovable-style mobile snap pager and desktop side-by-side split once a preview exists", () => {
    expect(pager).toContain("swipe between full-viewport chat and preview")
    expect(shell).toContain("data-siab-builder-pager")
    expect(shell).toContain("max-lg:snap-x max-lg:snap-mandatory")
    expect(shell).toContain("lg:contents")
    expect(shell).toContain("scrollToPane(\"preview\")")
    expect(shell).toContain("scrollToPane(\"chat\")")
    expect(shell).not.toContain("h-[46dvh]")
    expect(shell).toContain("pointer-events-none")
    expect(css).toContain("--siab-builder-chat-col: 28rem")
  })

  it("puts labelled logout on the agent header before preview, then on desktop preview chrome", () => {
    expect(shell).toContain("SignOutControl")
    expect(shell).toContain("iconOnly")
    expect(shell).toContain("showDesktopSignOut={!hasPreview}")
    expect(shell).toContain("desktopSignOut={<SignOutControl />}")
    expect(header).toContain("showDesktopSignOut")
    expect(header).toContain("desktopSignOut")
    expect(header).toContain("className=\"lg:hidden\"")
    expect(header).toContain("hasPreview ?")
    expect(header).toContain("data-siab-builder-preview-unread")
    expect(header).toContain("BuilderThemeToggle")
    expect(shell).toContain("FLOATING_PILL_CLASS")
    expect(shell).toContain("gap-1.5")
    expect(shell).toContain('size="icon"')
  })

  it("keeps keyboard hint tiles readable off the yellow ink token and desktop-only after the thread starts", () => {
    expect(composer).toContain("siab-builder-kbd")
    expect(composer).toContain("hidden flex-wrap")
    expect(composer).toContain("lg:flex")
    expect(composer).toContain("data-layout={layout}")
    expect(thread).toContain("choice.label")
    expect(thread).toContain("onChoice(choice.label)")
    expect(composer).toContain("hidden flex-wrap items-center gap-x-2 gap-y-1.5")
    expect(css).toContain("color: var(--foreground)")
    expect(css).not.toContain("color: var(--main-foreground)")
    expect(css).toContain("box-shadow: var(--shadow-hover)")
  })

  it("posts the iframe snapshot protocol after writes and renders leftover bold", () => {
    expect(shell).toContain("IFRAME_EDITOR_PROTOCOL_NAME")
    expect(shell).toContain("render.snapshot")
    expect(shell).not.toContain("sandbox=")
    expect(thread).toContain("splitBuilderSpeech")
    expect(shell).toContain("previewSnapshot")
    expect(shell).toContain("?rev=")
    expect(thread).toContain("BuilderSpeech")
    expect(thread).toContain("OPEN_PREVIEW_ACTION_ID")
    expect(thread).toContain("onOpenPreview")
    expect(thread).toContain("Bekijk je site")
  })

  it("names idle and busy presence phases", () => {
    expect(builderAgentStatus(false, false, null)).toBe("Klaar voor je eerste site")
    expect(builderAgentStatus(false, true, null)).toBe("Preview staat klaar")
    expect(builderAgentStatus(true, false, "leest")).toBe("Leest…")
    expect(builderAgentStatus(true, false, "schrijft")).toBe("Schrijft…")
    expect(builderAgentStatus(true, false, "bouwt")).toBe("Bouwt de homepage…")
  })

  it("treats an empty thread as the agent stage until the user replies or a site exists", () => {
    const empty = defaultBuilderMessages()
    const assistant = { role: "assistant" as const, text: "Welk vak doe je, en waar werk je?" }
    expect(empty).toEqual([])
    expect(isBuilderAgentStage(empty, null)).toBe(true)
    expect(isBuilderAgentStage([assistant], null)).toBe(true)
    expect(isBuilderAgentStage([...empty, { role: "user", text: "Ik ben kapper in Tilburg" }], null)).toBe(false)
    expect(isBuilderAgentStage(empty, "nieuw-bedrijf")).toBe(false)
    expect(messagesForBuilderSession([assistant], null)).toEqual([])
    expect(messagesForBuilderSession([assistant, { role: "user", text: "Ik ben kapper in Tilburg" }], null)).toEqual([
      { role: "user", text: "Ik ben kapper in Tilburg" },
    ])
    expect(messagesForBuilderSession([{ role: "user", text: "Ik ben kapper in Tilburg" }, assistant], null)).toEqual([
      { role: "user", text: "Ik ben kapper in Tilburg" },
      assistant,
    ])
    expect(builderPreviewActions(true, "nieuw-bedrijf")).toEqual([OPEN_PREVIEW_ACTION])
    expect(builderPreviewActions(false, "nieuw-bedrijf")).toBeUndefined()
    expect(builderPreviewActions(true, null)).toBeUndefined()
    expect(withOpenPreviewAction([assistant], true)[0]?.actions).toEqual([OPEN_PREVIEW_ACTION])
    expect(withOpenPreviewAction([{ ...assistant, actions: [OPEN_PREVIEW_ACTION] }], true)[0]?.actions).toEqual([OPEN_PREVIEW_ACTION])
  })

  it("uses thread-studio tiles, SIAB wordmark, and the shared operator charcoal in dark", () => {
    expect(header).toContain("data-siab-builder-status")
    expect(header).toContain("BuilderLogo")
    expect(header).toContain("sr-only")
    expect(header).not.toContain("BuilderAgentMark")
    expect(header).not.toContain(">SIAB<")
    expect(logo).toContain("/logos/logo-light.svg")
    expect(logo).toContain("/logos/logo-dark.svg")
    expect(header).not.toMatch(/>\s*S\s*</)
    expect(thread).toContain("data-siab-builder-thread")
    expect(thread).toContain("siab-builder-cursor")
    expect(thread).toContain("siab-builder-turn")
    expect(thread).toContain("max-w-[85%]")
    expect(thread).toContain("BUILDER_CHAT_WELL_CLASS")
    expect(thread).toContain("text-base leading-7")
    expect(thread).not.toContain("BuilderAgentMark")
    expect(thread).not.toContain("JIJ")
    expect(thread).not.toContain("neoChrome")
    expect(thread).not.toContain("userLetter")
    expect(thread).not.toContain("bg-main")
    expect(css).toContain("siab-builder-turn")
    expect(css).toContain("color-mix(in oklab, var(--border) 12%, transparent)")
    expect(composer).toContain("data-siab-builder-composer")
    expect(composer).toContain("BUILDER_CHAT_WELL_CLASS")
    expect(composer).not.toContain("neoTray")
    expect(composer).toContain("border-2 border-border bg-card p-2")
    expect(composer).toContain("shadow-none")
    expect(composer).toContain("Stuur")
    expect(composer).toContain('variant="ink"')
    expect(composer).toContain("min-width: 1024px")
    expect(composer).not.toContain('variant="brand"')
    expect(composer).not.toContain('variant="outline"')
    expect(composer).not.toContain("bg-main")
    expect(composer).not.toContain("Maak mijn site")
    expect(composer).not.toContain("Pas aan")
    expect(shell).not.toContain("Maak mijn site")
    expect(shell).not.toContain("Pas aan")
    expect(presence).toContain("Leest…")
    expect(presence).toContain("Bouwt de homepage…")
    expect(css).toContain(".siab-builder-cursor")
    expect(css).not.toContain("siab-builder-mark-pulse")
    expect(css).not.toContain("siab-builder-mark")
    expect(css).not.toContain(".dark [data-siab-builder]")
    const tokens = read("../../packages/ui/src/styles/shadcn.css")
    expect(tokens).toContain("--background: #242321")
    expect(tokens).toContain("--foreground: #f7f4ed")
    expect(tokens).toContain("color-mix(in srgb, #242321 96%, #f7f4ed 4%)")
    expect(tokens).toContain("--neo-slab: #ffffff")
    expect(tokens).toContain("color-mix(in srgb, var(--foreground) 30%, var(--background) 70%)")
    expect(tokens).not.toContain("--border: oklch(17% 0.012 90)")
    expect(tokens).not.toContain("color-mix(in srgb, #f7f4ed 45%, #242321 55%)")
    expect(tokens).not.toContain("--card: #000000")
    expect(tokens).not.toContain("--sidebar: #000000")
    expect(tokens).not.toContain("--border: #f7f4ed")
    expect(tokens).not.toContain("--background: #1c1c1c")
    expect(tokens).toContain("--muted-foreground: #eceae4")
    expect(tokens).not.toContain("--shadow-shadow-inverse")
    expect(tokens).not.toContain("--shadow-shadow-accent")
    expect(tokens).toContain("--shadow-shadow: 5px 5px 0px 0px var(--neo-slab)")
    expect(chrome).not.toContain("animate-bounce")
    expect(chrome).not.toContain("backdrop-blur")
    expect(chrome).not.toContain("rounded-lg")
    expect(shell).not.toContain("BuilderLogo")
    expect(shell).not.toContain("Bouw je website")
  })
})

describe("builder workspace routing", () => {
  it("sends a stale or unknown /builder/:slug back to a fresh /builder instead of 404", () => {
    const workspace = read("src/lib/builder/loadBuilderWorkspace.tsx")
    expect(workspace).toContain("if (!allowed) redirect(\"/builder\")")
    expect(workspace).not.toContain("if (!allowed) notFound()")
  })

  it("sends unauthenticated production builder traffic to the unified login page", () => {
    const workspace = read("src/lib/builder/loadBuilderWorkspace.tsx")
    expect(workspace).toContain('redirect(intent === "register" ? "/login?intent=register" : "/login")')
  })
})
