import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const read = (path: string) => readFileSync(path, "utf8")

describe("CMS agent panel chrome", () => {
  it("uses the builder composer and quiet thread turns", () => {
    const panel = read("src/components/layout/CmsAgentPanel.tsx")
    const css = read("src/styles/siab.css")
    const composer = read("src/components/builder/BuilderComposer.tsx")
    const button = read("../../packages/ui/src/components/button.tsx")

    expect(panel).toContain("data-siab-agent-chat")
    expect(panel).toContain("BuilderComposer")
    expect(panel).toContain("siab-builder-turn")
    expect(panel).toContain("BUILDER_CHAT_WELL_CLASS")
    expect(panel).toContain("siab-builder-cursor")
    expect(panel).toContain("minLength={8}")
    expect(panel).toContain("splitBuilderSpeech")
    expect(panel).toContain("sr-only")
    expect(panel).toContain("CMS_AGENT_GREETING")
    expect(panel).toContain("Wat moet er anders?")
    expect(panel).toContain("Bijv: Maak het thema groener en donkerder.")
    expect(panel).not.toContain("Sparkles")
    expect(panel).not.toContain("Toepassen")
    expect(panel).not.toContain('variant="brand"')
    expect(panel).not.toContain("bg-primary")
    expect(panel).not.toContain("shadow-sm")
    expect(css).toContain("[data-siab-agent-chat] .siab-builder-turn")
    expect(css).toContain("[data-siab-agent-chat] .siab-builder-kbd")
    expect(css).toContain("[data-siab-agent-chat] .siab-builder-cursor")
    expect(composer).toContain("minLength = 2")
    expect(composer).toContain("shadow-none")
    expect(button).toContain('ink: "bg-foreground text-background"')
    expect(button).toContain("neoPress")
    expect(button).not.toContain("neoPressAccent")
    expect(button).not.toContain("slab")
    expect(button).toContain("asChild")
    expect(button).toContain("blurAfterPointerClick")
    expect(button).toContain("handlePointerUp")
    expect(button).toContain("{ onPointerUp }")
  })

  it("clones the builder chat header onto the CMS agent drawer with a neo close tile", () => {
    const drawer = read("src/components/layout/CmsAgentDrawer.tsx")
    const header = read("src/components/builder/BuilderAgentHeader.tsx")

    expect(drawer).toContain("showCloseButton={false}")
    expect(drawer).toContain("BuilderLogo")
    expect(drawer).toContain("SheetClose")
    expect(drawer).toContain('variant="outline" size="icon" aria-label="Site agent"')
    expect(drawer).not.toContain('variant="default"')
    expect(drawer).toContain('variant="outline"')
    expect(drawer).toContain('size="icon"')
    expect(drawer).toContain("sm:max-w-[32rem]")
    expect(drawer).toContain("border-b-2 border-border bg-card px-4 py-3")
    expect(drawer).toContain('imgClassName="h-8 max-w-[11rem] sm:h-9 sm:max-w-[14rem]"')
    expect(header).toContain("border-b-2 border-border bg-card px-4 py-3")
    expect(header).toContain('imgClassName="h-8 max-w-[11rem] sm:h-9 sm:max-w-[14rem]"')
    expect(drawer).not.toContain("absolute top-4 right-4")
    expect(drawer).not.toContain("XIcon")
  })
})
