import fs from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

describe("preview customizer source contract", () => {
  it("hosts customer preview through an embedded renderer iframe contract", () => {
    const componentSource = fs.readFileSync(
      path.resolve(process.cwd(), "src/components/preview/PreviewCustomizer.tsx"),
      "utf8",
    )
    const routeSource = fs.readFileSync(
      path.resolve(process.cwd(), "src/app/(frontend)/(site-preview)/preview/[token]/page.tsx"),
      "utf8",
    )

    const desktopToolbarSource = fs.readFileSync(
      path.resolve(process.cwd(), "src/components/preview/preview-desktop-theme-toolbar.tsx"),
      "utf8",
    )

    expect(componentSource).toContain("/renderer-frame/preview/")
    expect(componentSource).toContain("data-siab-renderer-frame")
    expect(componentSource).toContain('const PREVIEW_THEME_TOOLBAR_CLOSE_EVENT = "siab:preview-theme-toolbar-close"')
    expect(componentSource).toContain("onFrameInteraction={() => window.dispatchEvent(new Event(PREVIEW_THEME_TOOLBAR_CLOSE_EVENT))}")
    expect(componentSource).toContain("onFocus={onFrameInteraction}")
    expect(componentSource).toContain("onPointerDown={onFrameInteraction}")
    expect(componentSource).toContain('frameDocument.addEventListener("pointerdown", onFrameInteraction, true)')
    expect(componentSource).toContain('frameDocument.addEventListener("focusin", onFrameInteraction, true)')
    expect(componentSource).toContain("document.activeElement === frameRef.current")
    expect(componentSource).toMatch(/<iframe\b/i)
    expect(componentSource.includes("@/components/editor/canvas/CanvasMode")).toBe(false)
    expect(componentSource.includes("<CanvasMode")).toBe(false)
    expect(componentSource).toContain("@siteinabox/contracts")
    expect(componentSource).toContain("IFRAME_EDITOR_PROTOCOL_NAME")
    expect(componentSource).toContain('type: "page.replace"')
    expect(componentSource).toContain('type: "theme.patch"')
    expect(componentSource).not.toContain("siab.renderer.")
    expect(componentSource).toContain("theme={themeState}")
    expect(componentSource).toContain("onThemeChange={handleThemeChange}")
    expect(componentSource).toContain("PreviewDesktopThemeToolbar")
    expect(componentSource).toContain("grid-cols-[auto_1fr]")
    expect(componentSource).toContain('className="pointer-events-none fixed inset-x-0 bottom-0 z-30 px-0 md:bottom-6 md:flex md:justify-center md:px-6"')
    expect(componentSource).toContain("pointer-events-auto relative grid w-full grid-cols-[auto_1fr] items-center gap-1 overflow-hidden")
    expect(componentSource).toContain("md:inline-flex md:w-auto md:grid-cols-none md:items-center md:gap-3")
    expect(componentSource).toContain("px-3 py-2")
    expect(componentSource).toContain("md:p-3")
    expect(componentSource).toContain("md:rounded-lg md:border-0 md:bg-background/90")
    expect(componentSource).toContain("ShineBorder")
    expect(componentSource).toContain("@/components/common/shine-border")
    expect(componentSource).not.toContain('<span className="md:hidden" aria-hidden />')
    expect(componentSource).not.toContain("ring-1 ring-white/40")
    expect(componentSource).not.toContain("border-white/30")
    expect(componentSource).not.toContain("md:border-white/20")
    expect(componentSource).toContain("flex justify-self-end items-center gap-2")
    expect(componentSource).toContain("h-12 w-12 rounded-md px-0 md:h-9 lg:w-auto lg:px-5")
    expect(componentSource).toContain("h-12 rounded-md px-4 md:h-9 md:px-5")
    expect(componentSource).toContain("justify-self-end")
    expect(componentSource).not.toContain("md:max-w-4xl")
    expect(componentSource).not.toContain("max-w-5xl")
    expect(componentSource).toContain("PreviewMobileChrome")
    expect(componentSource).toContain('className="w-full pb-24 md:pb-32"')
    expect(desktopToolbarSource).toContain("PalettePicker")
    expect(desktopToolbarSource).toContain("FontPicker")
    expect(desktopToolbarSource).toContain("ShapeControl")
    expect(desktopToolbarSource).not.toContain("DensityControl")
    expect(desktopToolbarSource).toContain('layout="inline"')
    expect(desktopToolbarSource).toContain('layout="segment"')
    expect(desktopToolbarSource).toContain("radiusLevels={RADIUS_PRESETS}")
    expect(desktopToolbarSource).not.toContain("DENSITY_PRESETS")
    expect(componentSource).not.toContain("<Dices")
    expect(componentSource).not.toContain("<RotateCcw")
    expect(componentSource).not.toContain("stylePresetLevels={STYLE_PRESETS}")
    expect(componentSource.includes('view="preview"')).toBe(false)
    expect(componentSource).not.toContain('aria-label={t("pagesNav")}')
    expect(componentSource).toContain('access.type === "grant"')
    expect(componentSource).toContain('const checkoutHref = access.type === "grant" ? `/${access.clientSlug}/checkout` : "#"')
    expect(componentSource).toContain('const reviewHref = access.type === "grant" ? `/${access.clientSlug}/review` : "#"')
    expect(componentSource).toContain("checkoutHref={checkoutHref}")
    expect(componentSource).toContain("reviewHref={reviewHref}")
    expect(componentSource).toContain('t("launchWebsite")')
    expect(componentSource).toContain('aria-label={t("reviewChanges")}')
    expect(componentSource).toContain('title={t("reviewChanges")}')
    expect(componentSource).toContain('<span className="sr-only lg:not-sr-only lg:ml-2">{t("reviewChanges")}</span>')
    expect(componentSource).toContain('t("paymentComplete")')
    expect(componentSource).toContain("paymentSatisfied={paymentSatisfied}")
    expect(componentSource).toContain("<CheckCircle2")
    expect(componentSource).toContain('t("reviewChanges")')
    expect(componentSource).toContain("paymentState?.status")
    expect(componentSource).not.toContain("Approve & Pay")
    expect(componentSource).not.toContain('t("approvePreview")')
    expect(componentSource.includes("@siteinabox/site-renderer")).toBe(false)
    expect(/<iframe\b/i.test(routeSource)).toBe(false)
  })
})
