import { readFileSync } from "node:fs"
import { join } from "node:path"
import { describe, expect, it } from "vitest"

const root = join(__dirname, "..", "..")
const read = (file: string) => readFileSync(join(root, file), "utf8")

describe("customer preview UI", () => {
  it("uses the dedicated customer preview renderer without editor metadata badges", () => {
    const customizer = read("src/components/preview/PreviewCustomizer.tsx")

    const desktopToolbar = read("src/components/preview/preview-desktop-theme-toolbar.tsx")

    expect(customizer.includes('view: "preview"')).toBe(false)
    expect(customizer).toContain("data-siab-renderer-frame")
    expect(customizer).toContain('export { PREVIEW_THEME_TOOLBAR_CLOSE_EVENT }')
    expect(customizer).toContain("@/lib/preview/preview-theme-events")
    expect(customizer).toContain("onFrameInteraction={() => window.dispatchEvent(new Event(PREVIEW_THEME_TOOLBAR_CLOSE_EVENT))}")
    expect(customizer).toContain("onFocus={onFrameInteraction}")
    expect(customizer).toContain("onPointerDown={onFrameInteraction}")
    expect(customizer).toContain('frameDocument.addEventListener("pointerdown", onFrameInteraction, true)')
    expect(customizer).toContain('frameDocument.addEventListener("focusin", onFrameInteraction, true)')
    expect(customizer).toContain("document.activeElement === frameRef.current")
    expect(customizer).toContain("/renderer-frame/preview/")
    expect(customizer.includes('view="preview"')).toBe(false)
    expect(customizer.includes("<CanvasMode")).toBe(false)
    expect(customizer).toContain('variant="success"')
    expect(customizer).toContain('variant="secondary"')
    expect(customizer).toContain("disabled")
    expect(customizer).toContain('t("paymentComplete")')
    expect(customizer).toContain("reviewHref")
    expect(customizer).toContain("PreviewDesktopThemeToolbar")
    expect(customizer).toContain("normalizePreviewThemeForSave")
    expect(customizer).toContain("PreviewMobileChrome")
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain("MobileFloatingPill")
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain('position="top-left"')
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain('position="top-right"')
    expect(desktopToolbar).toContain("PalettePicker")
    expect(desktopToolbar).toContain("FontPicker")
    expect(desktopToolbar).toContain("ShapeControl")
    expect(desktopToolbar).not.toContain("DensityControl")
    expect(desktopToolbar).toContain('layout="inline"')
    expect(desktopToolbar).toContain('layout="segment"')
    expect(customizer).toContain("grid-cols-[auto_1fr]")
    expect(customizer).toContain("pointer-events-none fixed inset-x-0 bottom-0 z-30 px-0 md:bottom-6 md:flex md:justify-center md:px-6")
    expect(customizer).toContain("pointer-events-auto relative grid w-full grid-cols-[auto_1fr] items-center gap-1 overflow-hidden")
    expect(customizer).not.toContain("ShineBorder")
    expect(customizer).not.toContain("contentClassName")
    expect(customizer).not.toContain("rgba(255,255,255,0.95)")
    expect(customizer).not.toContain("shine-border")
    expect(customizer).toContain("md:inline-flex md:w-auto md:grid-cols-none md:items-center md:gap-3")
    expect(customizer).toContain("px-3 py-2")
    expect(customizer).toContain("md:p-3")
    expect(customizer).toContain("md:rounded-lg")
    expect(customizer).not.toContain('<span className="md:hidden" aria-hidden />')
    expect(customizer).toContain("flex justify-self-end items-center gap-2 md:justify-self-auto")
    expect(customizer).toContain("h-12 w-12 rounded-md px-0 md:h-9 lg:w-auto lg:px-5")
    expect(customizer).toContain("h-12 rounded-md px-4 md:h-9 md:px-5")
    expect(customizer).toContain("justify-self-end")
    expect(customizer).not.toContain("justify-self-center")
    expect(customizer).not.toContain("md:max-w-4xl")
    expect(customizer).not.toContain("max-w-5xl")
    expect(customizer).toContain("hidden md:block")
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain("md:hidden")
    expect(customizer).not.toContain('size="lg"')
    expect(customizer).toContain('lg:not-sr-only lg:ml-2">{t("reviewChanges")}')
    expect(customizer).toContain("md:border md:border-border")
    expect(customizer).not.toContain("PopoverContent")
    expect(customizer).not.toContain("SegmentedPill")
    expect(customizer).not.toContain("ring-1 ring-white/40")
    expect(customizer).not.toContain("border-white/30")
    expect(customizer).not.toContain("md:border-white/20")
    expect(customizer).toContain("md:bg-background md:p-3 md:shadow-none")
    expect(customizer).not.toContain("md:shadow-2xl")
    expect(customizer).not.toContain("md:bg-background/90")
    expect(customizer).not.toContain("md:backdrop-blur-xl")
    expect(read("src/components/preview/preview-desktop-theme-toolbar.tsx")).toContain('aria-label={previewT("themeControls")}')
    expect(customizer).toContain('className="h-dvh w-full overflow-hidden"')
    expect(customizer).toContain('className="relative h-dvh min-h-[32rem] w-full overflow-hidden bg-background"')
    expect(customizer).toContain('"block h-full min-h-[32rem] w-full border-0 bg-transparent transition-opacity duration-150"')
    expect(customizer).not.toContain("preview-renderer-frame-auto-height")
    expect(customizer).not.toContain("measurePreviewFrameDocumentHeight")
    expect(customizer).not.toContain("ResizeObserver")
    expect(customizer).not.toContain("MutationObserver")
    expect(customizer).not.toContain('scrolling="no"')
    expect(customizer).not.toContain("h-[calc(100dvh-9rem)]")
    expect(customizer).not.toContain("sticky top-0 z-20 flex items-center justify-center border-b")
    expect(customizer).not.toContain("stylesReady")
    expect(customizer).not.toContain("pagesNav")

    const frameRuntime = read("src/components/renderer-frame/RendererFrameRuntime.tsx")
    const rendererStyles = read("src/styles/generated-site-renderer.css")
    expect(frameRuntime).toContain("renderer-frame-preview-viewport")
    expect(frameRuntime).toContain("window.parent")
    expect(frameRuntime).toContain("data-siab-preview-viewport")
    expect(rendererStyles).toContain(':is([data-siab-preview-viewport="true"], [data-siab-editor-parent-scroll="true"]) .min-h-screen')
    expect(rendererStyles).toContain("--siab-preview-viewport-height")
  })

  it("guards customer preview media with preview grants instead of making tenant media public", () => {
    const route = read("src/app/(payload)/siab-media/[tenantId]/[...path]/route.ts")
    const access = read("src/lib/preview/previewAccess.ts")

    expect(route).toContain("previewAuth.api.getSession")
    expect(route).toContain("hasActivePreviewGrantForTenant")
    expect(route).toContain("isPreviewMediaHost")
    expect(access).toContain("hasActivePreviewGrantForTenant")
  })

  it("exposes a guarded review route and stores customer notes on the current preview run", () => {
    const page = read("src/app/(frontend)/(site-preview)/[clientSlug]/review/page.tsx")
    const action = read("src/app/(frontend)/(site-preview)/[clientSlug]/review/actions.ts")
    const review = read("src/components/preview/PreviewReview.tsx")

    expect(page).toContain("isPreviewHost")
    expect(page).toContain("previewAuth.api.getSession")
    expect(action).toContain("clientApproval")
    expect(action).toContain("reviewNotes")
    expect(review).toContain("Textarea")
    expect(review).toContain('grid grid-cols-2')
    expect(review).toContain('t("reviewClose")')
    expect(review).toContain('t("reviewSend")')
    expect(review).not.toContain("Rocket")
    expect(review).not.toContain("checkoutHref")
    expect(page).not.toContain("checkoutHref=")
  })

  it("renders checkout as an accessible two-decision authoritative-profile flow", () => {
    const checkout = read("src/components/preview/PreviewCheckout.tsx")
    const stepper = read("src/components/preview/CheckoutStepper.tsx")
    const page = read("src/app/(frontend)/(site-preview)/[clientSlug]/checkout/page.tsx")
    const actions = read("src/app/(frontend)/(site-preview)/[clientSlug]/checkout/actions.ts")
    const primaryAction = read("src/components/preview/checkout/CheckoutPrimaryAction.tsx")

    expect(checkout).toContain("type CheckoutStep = CheckoutDecision")
    expect(checkout).toContain("CheckoutStepper")
    expect(stepper).toContain("grid-cols-3")
    expect(stepper).toContain("grid-cols-2")
    expect(stepper).toContain("grid-cols-4")
    expect(stepper).toContain("bg-brand text-brand-foreground")
    expect(stepper).toContain('aria-current={active ? "step" : undefined}')
    expect(checkout).toContain('id: "review"')
    expect(checkout).toContain('src="/logos/logo-light.svg"')
    expect(checkout).toContain('src="/logos/logo-dark.svg"')
    expect(checkout).toContain("domainReady")
    expect(checkout).toContain("MobileCheckoutBar")
    expect(primaryAction).toContain("checkoutDomainOccupied")
    expect(checkout).toContain("border-warning")
    expect(checkout).not.toContain('id="checkout-domain-unavailable"')
    expect(checkout).not.toContain("checkoutDomainUnavailableTitle")
    expect(checkout).not.toContain("checkoutDomainAvailableDetail")
    expect(checkout).toContain("text-warning")
    expect(checkout).toContain("text-success")
    expect(checkout).toContain("const domainDescriptionId = domainInputState === \"error\"")
    expect(checkout).toContain('aria-invalid={domainInputState === "error" ? true : undefined}')
    expect(checkout).toContain("aria-describedby={domainDescriptionId}")
    expect(checkout).toContain('aria-live="polite"')
    expect(checkout).toContain('role="alert"')
    expect(checkout).toContain("stepHeadingRef.current?.focus()")
    expect(primaryAction).toContain('action.label === "domain_unavailable" ? "ghost"')
    expect(checkout).not.toContain('aria-invalid={domainInputState === "error" || domainInputState === "warning"}')
    expect(checkout).toContain("requestSubmit()")
    expect(checkout).toContain("window.setTimeout")
    expect(checkout).toContain("domainFormRef")
    expect(checkout).toContain("prewarmHref")
    expect(checkout).toContain("fetch(prewarmHref")
    expect(checkout).toContain("AbortController")
    expect(checkout).toContain("credentials: \"same-origin\"")
    expect(checkout).toContain("controller.abort()")
    expect(checkout).toContain("const recommendedDomainExtensions")
    expect(checkout).toContain("const fallbackDomainExtensions")
    expect(checkout).toContain("const recommendedDomainSearchDomains = React.useMemo")
    expect(checkout).toContain("const fallbackDomainSearchDomains = React.useMemo")
    expect(checkout).toContain("const visibleDomainSearchDomains = React.useMemo")
    expect(checkout).toContain("const readyCount = recommendedResults.filter(checkoutReadyDomainResult).length")
    expect(checkout).toContain("Promise.all(domains.map(async (domain) =>")
    expect(checkout).toContain("h-12 rounded-xl pr-11 pl-[42px] text-base font-medium")
    expect(checkout).toContain('div className="relative scroll-mb-28 min-w-0 overflow-hidden rounded-[17px]')
    expect(checkout).toContain('Card data-checkout-main-card className="gap-0 rounded-none border-0 py-0 shadow-none"')
    expect(checkout).toContain('before:from-brand before:to-brand/20')
    expect(checkout).toContain("focus-visible:border-success")
    expect(checkout).toContain("size-5 text-success")
    expect(stepper).toContain('active && "border-border bg-card text-foreground shadow-sm"')
    expect(stepper).toContain('complete && "bg-success/10')
    expect(stepper).toContain("min-h-[50px]")
    expect(stepper).toContain("min-[560px]:min-h-[58px]")
    expect(checkout).toContain("bg-card/95")
    expect(checkout).toContain("setCheckedDomain(null)")
    expect(checkout).toContain("domainFormRef.current?.requestSubmit()")
    expect(checkout).not.toContain("setCheckedDomain(option.domain)")
    expect(checkout).not.toContain("selectedSuggestion")
    expect(primaryAction).toContain('t("checkoutStartPaymentAmount", { amount: dueNow })')
    expect(checkout).toContain('<X className="size-[15px]"')
    expect(checkout).toContain("<ArrowLeft")
    expect(checkout).toContain('variant="success"')
    expect(checkout).not.toContain("ChevronLeft")
    expect(checkout).toContain("<Label")
    expect(checkout).toContain("checkoutDomainLabel")
    expect(checkout).toContain("checkoutPartyRegistered")
    expect(checkout).toContain("checkoutPartyInFormation")
    expect(checkout).toContain("checkoutMigrationSourceLegend")
    expect(checkout).not.toContain("checkoutMigrationAssistedTitle")
    expect(checkout).not.toContain("businessUseDeclarationText")
    expect(checkout).toContain("expectedProfileVersion")
    expect(checkout).toContain("expectedProfileKey")
    expect(checkout).toContain("expectedTermsVersion")
    expect(checkout).toContain("expectedPrivacyVersion")
    expect(checkout).toContain("latestDomainRequestTokenRef")
    expect(checkout).toContain("latestProfileRequestTokenRef")
    expect(checkout).not.toContain('name="registrantEmail"')
    expect(checkout).not.toContain('name="companyName"')
    expect(actions).toContain("loadLatestCheckoutProfile")
    expect(actions).toContain("domainRegistrantFromCheckoutProfile")
    expect(actions).not.toContain("registrantFromFormData")
    expect(page).toContain("deriveRegistrantDefaults")
    expect(page).toContain("loadLatestCheckoutProfile")
    expect(page).toContain("initialProfile={initialProfile}")
    expect(page).toContain("saveProfileAction")
    expect(page).toContain("prewarmHref")
    expect(page).toContain("/checkout/prewarm")
    expect(page).toContain("const selectedDomain = acceptedResume?.domain ??")
    expect(page).toContain(
      'domainOrder.status === "ready_to_register" ? domainOrder.domain : null',
    )
    expect(page).toContain("currentDomain={selectedDomain}")
    expect(page).toContain("domainReady={Boolean(selectedDomain)}")
    expect(page).not.toContain("currentDomain={domainOrder.domain ?? context.tenant.domain}")
    const prewarmRoute = read("src/app/(frontend)/(site-preview)/[clientSlug]/checkout/prewarm/route.ts")
    expect(prewarmRoute).toContain("requirePreviewCheckoutContext")
    expect(prewarmRoute).toContain("loginOpenProvider")
    expect(prewarmRoute).toContain("status: 204")
    expect(prewarmRoute).not.toContain("checkAndRecordPreviewDomainOrder")
    expect(prewarmRoute).not.toContain("suggestAvailablePreviewDomainBatch")
    expect(checkout).not.toContain("suggestionsHref")
    expect(checkout).not.toContain("DomainSuggestions")
  })

  it("defaults the CMS frontend shell including previews to dark mode", () => {
    const layout = read("src/app/(frontend)/layout.tsx")

    expect(layout).toContain('defaultTheme="dark"')
    expect(layout).toContain("enableSystem")
  })
})
