import { readFileSync } from "node:fs"
import { join } from "node:path"
import { describe, expect, it } from "vitest"

const root = join(__dirname, "..", "..")
const read = (file: string) => readFileSync(join(root, file), "utf8")

describe("customer preview UI", () => {
  it("uses the dedicated customer preview renderer without editor metadata badges", () => {
    const customizer = read("src/components/preview/PreviewCustomizer.tsx")

    const desktopToolbar = read("src/components/preview/preview-desktop-theme-toolbar.tsx")

    expect(customizer.includes('view: "preview"')).toBe(false)
    expect(customizer).toContain("data-siab-renderer-frame")
    expect(customizer).toContain('export { PREVIEW_THEME_TOOLBAR_CLOSE_EVENT }')
    expect(customizer).toContain("@/lib/preview/preview-theme-events")
    expect(customizer).toContain("onFrameInteraction={() => window.dispatchEvent(new Event(PREVIEW_THEME_TOOLBAR_CLOSE_EVENT))}")
    expect(customizer).toContain("onFocus={onFrameInteraction}")
    expect(customizer).toContain("onPointerDown={onFrameInteraction}")
    expect(customizer).toContain('frameDocument.addEventListener("pointerdown", onFrameInteraction, true)')
    expect(customizer).toContain('frameDocument.addEventListener("focusin", onFrameInteraction, true)')
    expect(customizer).toContain("document.activeElement === frameRef.current")
    expect(customizer).toContain("/renderer-frame/preview/")
    expect(customizer.includes('view="preview"')).toBe(false)
    expect(customizer.includes("<CanvasMode")).toBe(false)
    expect(customizer).toContain('variant="success"')
    expect(customizer).toContain('variant="secondary"')
    expect(customizer).toContain("disabled")
    expect(customizer).toContain('t("paymentComplete")')
    expect(customizer).toContain("reviewHref")
    expect(customizer).toContain("PreviewDesktopThemeToolbar")
    expect(customizer).toContain("normalizePreviewThemeForSave")
    expect(customizer).toContain("PreviewMobileChrome")
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain("MobileFloatingPill")
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain('position="top-left"')
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain('position="top-right"')
    expect(desktopToolbar).toContain("PalettePicker")
    expect(desktopToolbar).toContain("FontPicker")
    expect(desktopToolbar).toContain("ShapeControl")
    expect(desktopToolbar).not.toContain("DensityControl")
    expect(desktopToolbar).toContain('layout="inline"')
    expect(desktopToolbar).toContain('layout="segment"')
    expect(customizer).toContain("grid-cols-[auto_1fr]")
    expect(customizer).toContain("pointer-events-none fixed inset-x-0 bottom-0 z-30 px-0 md:bottom-6 md:flex md:justify-center md:px-6")
    expect(customizer).toContain("pointer-events-auto w-full shadow-lg md:w-auto md:rounded-lg md:shadow-none")
    expect(customizer).toContain("ShineBorder")
    expect(customizer).toContain("rgba(255,255,255,0.95)")
    expect(customizer).toContain("contentClassName")
    expect(customizer).toContain("md:inline-flex md:w-auto md:grid-cols-none md:items-center md:gap-3")
    expect(customizer).toContain("px-3 py-2")
    expect(customizer).toContain("md:p-3")
    expect(customizer).toContain("md:rounded-lg")
    expect(customizer).not.toContain('<span className="md:hidden" aria-hidden />')
    expect(customizer).toContain("flex justify-self-end items-center gap-2 md:justify-self-auto")
    expect(customizer).toContain("h-12 w-12 rounded-md px-0 md:h-9 lg:w-auto lg:px-5")
    expect(customizer).toContain("h-12 rounded-md px-4 md:h-9 md:px-5")
    expect(customizer).toContain("justify-self-end")
    expect(customizer).not.toContain("justify-self-center")
    expect(customizer).not.toContain("md:max-w-4xl")
    expect(customizer).not.toContain("max-w-5xl")
    expect(customizer).toContain("hidden md:block")
    expect(read("src/components/preview/preview-mobile-chrome.tsx")).toContain("md:hidden")
    expect(customizer).not.toContain('size="lg"')
    expect(customizer).toContain('lg:not-sr-only lg:ml-2">{t("reviewChanges")}')
    expect(customizer).toContain("md:border-0")
    expect(customizer).not.toContain("PopoverContent")
    expect(customizer).not.toContain("SegmentedPill")
    expect(customizer).not.toContain("ring-1 ring-white/40")
    expect(customizer).not.toContain("border-white/30")
    expect(customizer).not.toContain("md:border-white/20")
    expect(customizer).toContain("md:shadow-none")
    expect(customizer).not.toContain("md:shadow-2xl")
    expect(customizer).not.toContain("md:bg-background/90")
    expect(customizer).not.toContain("md:backdrop-blur-xl")
    expect(read("src/components/common/shine-border.tsx")).not.toContain("mask-composite:exclude")
    expect(read("src/components/common/shine-border.tsx")).not.toContain("-webkit-mask-composite")
    expect(read("src/components/common/shine-border.tsx")).not.toContain("will-change-[background-position]")
    expect(read("src/components/common/shine-border.tsx")).toContain("shine-border-lid")
    expect(read("src/components/preview/preview-desktop-theme-toolbar.tsx")).toContain('aria-label={previewT("themeControls")}')
    expect(customizer).toContain('className="h-dvh w-full overflow-hidden"')
    expect(customizer).toContain('className="relative h-dvh min-h-[32rem] w-full overflow-hidden bg-background"')
    expect(customizer).toContain('"block h-full min-h-[32rem] w-full border-0 bg-transparent transition-opacity duration-150"')
    expect(customizer).not.toContain("preview-renderer-frame-auto-height")
    expect(customizer).not.toContain("measurePreviewFrameDocumentHeight")
    expect(customizer).not.toContain("ResizeObserver")
    expect(customizer).not.toContain("MutationObserver")
    expect(customizer).not.toContain('scrolling="no"')
    expect(customizer).not.toContain("h-[calc(100dvh-9rem)]")
    expect(customizer).not.toContain("sticky top-0 z-20 flex items-center justify-center border-b")
    expect(customizer).not.toContain("stylesReady")
    expect(customizer).not.toContain("pagesNav")

    const frameRuntime = read("src/components/renderer-frame/RendererFrameRuntime.tsx")
    const rendererStyles = read("src/styles/generated-site-renderer.css")
    expect(frameRuntime).toContain("renderer-frame-preview-viewport")
    expect(frameRuntime).toContain("window.parent")
    expect(frameRuntime).toContain("data-siab-preview-viewport")
    expect(rendererStyles).toContain(':is([data-siab-preview-viewport="true"], [data-siab-editor-parent-scroll="true"]) .min-h-screen')
    expect(rendererStyles).toContain("--siab-preview-viewport-height")
  })

  it("guards customer preview media with preview grants instead of making tenant media public", () => {
    const route = read("src/app/(payload)/siab-media/[tenantId]/[...path]/route.ts")
    const access = read("src/lib/preview/previewAccess.ts")

    expect(route).toContain("previewAuth.api.getSession")
    expect(route).toContain("hasActivePreviewGrantForTenant")
    expect(route).toContain("isPreviewMediaHost")
    expect(access).toContain("hasActivePreviewGrantForTenant")
  })

  it("exposes a guarded review route and stores customer notes on the current preview run", () => {
    const page = read("src/app/(frontend)/(site-preview)/[clientSlug]/review/page.tsx")
    const action = read("src/app/(frontend)/(site-preview)/[clientSlug]/review/actions.ts")
    const review = read("src/components/preview/PreviewReview.tsx")

    expect(page).toContain("isPreviewHost")
    expect(page).toContain("previewAuth.api.getSession")
    expect(action).toContain("clientApproval")
    expect(action).toContain("reviewNotes")
    expect(review).toContain("Textarea")
    expect(review).toContain('grid grid-cols-2')
    expect(review).toContain('t("reviewClose")')
    expect(review).toContain('t("reviewSend")')
    expect(review).not.toContain("Rocket")
    expect(review).not.toContain("checkoutHref")
    expect(page).not.toContain("checkoutHref=")
  })

  it("renders checkout as a branded two-step flow with domain fee states", () => {
    const checkout = read("src/components/preview/PreviewCheckout.tsx")
    const stepper = read("src/components/preview/CheckoutStepper.tsx")
    const page = read("src/app/(frontend)/(site-preview)/[clientSlug]/checkout/page.tsx")

    expect(checkout).toContain('type CheckoutStep = "domain" | "payment"')
    expect(checkout).toContain("CheckoutStepper")
    expect(stepper).toContain("grid-cols-2")
    expect(stepper).toContain("grid-cols-4")
    expect(stepper).toContain("bg-primary text-primary-foreground")
    expect(checkout).not.toContain('id: "details"')
    expect(checkout).toContain('src="/logos/logo-light.svg"')
    expect(checkout).toContain('src="/logos/logo-dark.svg"')
    expect(checkout).toContain("checkoutDomainExtraFeeInline")
    expect(checkout).toContain("domainReady")
    expect(checkout).toContain("CheckoutActionBar")
    expect(checkout).toContain("checkoutDomainOccupied")
    expect(checkout).toContain("border-warning")
    expect(checkout).toContain("checkout-domain-unavailable")
    expect(checkout).toContain("checkout-domain-available")
    expect(checkout).toContain("checkoutDomainUnavailableTitle")
    expect(checkout).toContain("checkoutDomainAvailableTitle")
    expect(checkout).toContain("text-warning")
    expect(checkout).toContain("text-success")
    expect(checkout).toContain("const domainDescriptionId = domainInputState === \"success\"")
    expect(checkout).toContain('aria-invalid={domainInputState === "error" ? true : undefined}')
    expect(checkout).toContain("aria-describedby={domainDescriptionId}")
    expect(checkout).toContain('variant={unavailable ? "ghost" : "default"}')
    expect(checkout).toContain('variant="ghost"')
    expect(checkout).toContain("border border-transparent")
    expect(checkout).toContain("ring-2 ring-success/70")
    expect(checkout).toContain("min-h-12")
    expect(checkout).toContain("p-2.5")
    expect(checkout).toContain("bg-success/10")
    expect(checkout).toContain("shadow-success/10")
    expect(checkout).toContain("hover:bg-success/15")
    expect(checkout).toContain("dark:bg-success/10")
    expect(checkout).toContain("bg-muted/30")
    expect(checkout).not.toContain("ring-2 ring-success hover")
    expect(checkout).not.toContain('aria-invalid={domainInputState === "error" || domainInputState === "warning"}')
    expect(checkout).toContain("break-all text-base font-medium text-foreground")
    expect(checkout).toContain("flex items-center gap-2 text-base font-medium text-foreground")
    expect(checkout).toContain("requestSubmit()")
    expect(checkout).toContain("window.setTimeout")
    expect(checkout).toContain("domainFormRef")
    expect(checkout).toContain("prewarmHref")
    expect(checkout).toContain("fetch(prewarmHref")
    expect(checkout).toContain("suggestionsHref")
    expect(checkout).toContain("AbortController")
    expect(checkout).toContain("credentials: \"same-origin\"")
    expect(checkout).toContain("controller.abort()")
    expect(checkout).toContain("suggestionsAbortRef.current?.abort()")
    expect(checkout).toContain("suggestionsAbortRef.current !== controller")
    expect(checkout).toContain("previewDomainCandidates")
    expect(checkout).toContain("placeholderSuggestionsForDomain")
    expect(checkout).toContain("checking")
    expect(checkout).toContain("suggestionsApplyToCurrentInput")
    expect(checkout).toContain("const primaryDomainUnavailable = Boolean(")
    expect(checkout).toContain('["unavailable", "premium"].includes(checkState.status ?? "")')
    expect(checkout).toContain("if (!primaryDomainUnavailable) return")
    expect(checkout).toContain("const suggestions = primaryDomainUnavailable && suggestionsApplyToCurrentInput ? suggestionsState.suggestions : []")
    expect(checkout).toContain("const placeholderSuggestions = primaryDomainUnavailable && domainLooksCheckable")
    expect(checkout).toContain("step === \"domain\" && domainLooksCheckable && primaryDomainUnavailable")
    expect(checkout).toContain("if (onSelect) {")
    expect(checkout).toContain("h-12 pr-12 text-base font-medium md:h-13 md:text-lg")
    expect(checkout).toContain('CardTitle className="text-xl md:text-2xl"')
    expect(checkout).toContain('CardDescription className="text-base"')
    expect(checkout).toContain("grid gap-3 rounded-md border p-4 text-base")
    expect(checkout).toContain("focus-visible:border-success")
    expect(checkout).toContain("size-5 text-success")
    expect(stepper).toContain('(active || complete) && "bg-primary text-primary-foreground"')
    expect(stepper).toContain('complete && index + 1 === activeIndex && "rounded-r-none"')
    expect(stepper).toContain('active && index > 0 && "rounded-l-none"')
    expect(checkout).toContain("bg-background/95")
    expect(checkout).toContain("md:bg-card")
    expect(checkout).toContain("setCheckedDomain(null)")
    expect(checkout).toContain("domainFormRef.current?.requestSubmit()")
    expect(checkout).not.toContain("setCheckedDomain(option.domain)")
    expect(checkout).not.toContain("selectedSuggestion")
    expect(checkout).toContain('`${t("checkoutStartPayment")} - ${totalPriceLabel}`')
    expect(checkout).toContain("<X")
    expect(checkout).toContain("<ArrowLeft")
    expect(checkout).toContain('variant="success"')
    expect(checkout).toContain("formatDomainHolderName")
    expect(checkout).not.toContain("ChevronLeft")
    expect(checkout).not.toContain("checkoutDomainIncluded)")
    expect(checkout).not.toContain("checkoutSecureBadge")
    expect(checkout).not.toContain("checkoutDescription")
    expect(checkout).not.toContain("checkoutTotalBadge")
    expect(checkout).not.toContain("checkoutDetailsOverviewTitle")
    expect(checkout).not.toContain("checkoutRenewalTitle")
    expect(checkout).not.toContain("checkoutEdit")
    expect(checkout).not.toContain("Pencil")
    expect(checkout).not.toContain("checkoutSummaryTitle")
    expect(checkout).not.toContain("<Label")
    expect(checkout).not.toContain("checkoutDomainLabel")
    expect(checkout).not.toContain("complete ? <CheckCircle2")
    expect(page).toContain("deriveRegistrantDefaults")
    expect(page).toContain("registrant={registrant}")
    expect(page).toContain("prewarmHref")
    expect(page).toContain("/checkout/prewarm")
    expect(page).toContain("suggestionsHref")
    expect(page).toContain('const selectedDomain = domainOrder.status === "ready_to_register" ? domainOrder.domain : null')
    expect(page).toContain("currentDomain={selectedDomain}")
    expect(page).toContain("domainReady={Boolean(selectedDomain)}")
    expect(page).not.toContain("currentDomain={domainOrder.domain ?? context.tenant.domain}")
    const prewarmRoute = read("src/app/(frontend)/(site-preview)/[clientSlug]/checkout/prewarm/route.ts")
    expect(prewarmRoute).toContain("requirePreviewCheckoutContext")
    expect(prewarmRoute).toContain("loginOpenProvider")
    expect(prewarmRoute).toContain("status: 204")
    expect(prewarmRoute).not.toContain("checkAndRecordPreviewDomainOrder")
    expect(prewarmRoute).not.toContain("suggestAvailablePreviewDomainBatch")
    const suggestionsRoute = read("src/app/(frontend)/(site-preview)/[clientSlug]/checkout/suggestions/route.ts")
    expect(suggestionsRoute).toContain("requirePreviewCheckoutContext")
    expect(suggestionsRoute).toContain("suggestAvailablePreviewDomainBatch")
    expect(suggestionsRoute).toContain("NextResponse.json")
    expect(suggestionsRoute).toContain("existingDomains")
  })

  it("defaults the CMS frontend shell including previews to dark mode", () => {
    const layout = read("src/app/(frontend)/layout.tsx")

    expect(layout).toContain('defaultTheme="dark"')
    expect(layout).toContain("enableSystem")
  })
})
