import { colorSchemes, fontSchemes, shapeSchemes } from "./resolve"

const shades = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const
const selector = (kind: string, id: string) => `:where(.rt-canvas,[data-siab-theme-scope])[data-theme-${kind}="${id}"]`
const declarations = (values: Record<string, string>) => Object.entries(values).map(([name, value]) => `${name}:${value}`).join(";")

const hues: Record<string, number> = { monochrome: 0, "blue-professional": 264, "red-confident": 25, "emerald-calm": 165, "amber-warm": 75, "terracotta-warm": 35 }
/** Soft pastel dark brand (pre-500-lift) for schemes that read better at 400. */
const softDarkBrand = new Set(["red-confident", "amber-warm"])
/** Amber stays yellow in both modes, with only a modest light→dark lift. */
const yellowBrand = new Set(["amber-warm"])

const semantic = (id: string, mode: (typeof colorSchemes)[keyof typeof colorSchemes]["light"], dark: boolean) => {
  const hue = hues[id] ?? 0
  const darkBrand = softDarkBrand.has(id) ? mode.accent[400]! : mode.accent[500]!
  // Amber light: yellow-gold 500 (not brown 700). Dark: brighter 400. Same family, small lift.
  const lightPrimary = yellowBrand.has(id) ? mode.accent[500]! : mode.accent[700]!
  const lightColorAccent = yellowBrand.has(id) ? mode.accent[500]! : mode.accent[600]!
  const primaryForeground = dark || yellowBrand.has(id)
    ? `oklch(0.145 0.012 ${hue})`
    : mode.onAccent
  return ({
  "--background": mode.surface,
  "--foreground": mode.ink,
  "--card": dark ? `oklch(0.205 0.014 ${hue})` : `oklch(0.998 0.003 ${hue})`,
  "--card-foreground": mode.ink,
  "--popover": dark ? `oklch(0.205 0.014 ${hue})` : `oklch(0.998 0.003 ${hue})`,
  "--popover-foreground": mode.ink,
  "--primary": dark ? darkBrand : lightPrimary,
  "--primary-foreground": primaryForeground,
  "--secondary": dark ? `oklch(0.269 0.016 ${hue})` : `oklch(0.97 0.012 ${hue})`,
  "--secondary-foreground": mode.ink,
  "--muted": dark ? `oklch(0.205 0.014 ${hue})` : `oklch(0.97 0.012 ${hue})`,
  "--muted-foreground": mode.muted,
  // Soft brand wash both modes (light tint / dark shade) — not a generic muted surface.
  "--accent": dark ? mode.accent[900]! : mode.accent[100]!,
  "--accent-foreground": mode.ink,
  "--border": mode.rule,
  "--input": mode.rule,
  "--ring": yellowBrand.has(id) ? mode.accent[400]! : mode.accent[500]!,
  "--destructive": dark ? "#f87171" : "#dc2626",
  "--destructive-foreground": "#ffffff",
  "--success": dark ? "#34d399" : "#059669",
  "--success-foreground": dark ? "#030712" : "#ffffff",
  "--warning": dark ? "#fbbf24" : "#d97706",
  "--warning-foreground": "#030712",
  "--rating": dark ? "#fcd34d" : "#eab308",
  "--overlay": dark ? "rgba(0,0,0,.64)" : "rgba(0,0,0,.56)",
  "--on-media": "#ffffff",
  "--color-bg": mode.surface,
  "--color-ink": mode.ink,
  "--color-ink-muted": mode.muted,
  "--color-accent": dark ? darkBrand : lightColorAccent,
  })
}

const exactMonochrome = {
  light: {
    "--background": "oklch(1 0 0)", "--foreground": "oklch(0.145 0 0)", "--card": "oklch(1 0 0)", "--card-foreground": "oklch(0.145 0 0)",
    "--popover": "oklch(1 0 0)", "--popover-foreground": "oklch(0.145 0 0)", "--primary": "oklch(0.205 0 0)", "--primary-foreground": "oklch(0.985 0 0)",
    "--secondary": "oklch(0.97 0 0)", "--secondary-foreground": "oklch(0.205 0 0)", "--muted": "oklch(0.97 0 0)", "--muted-foreground": "oklch(0.556 0 0)",
    "--accent": "oklch(0.97 0 0)", "--accent-foreground": "oklch(0.205 0 0)", "--destructive": "oklch(0.58 0.22 27)", "--border": "oklch(0.922 0 0)",
    "--input": "oklch(0.922 0 0)", "--ring": "oklch(0.708 0 0)",
  },
  dark: {
    "--background": "oklch(0.145 0 0)", "--foreground": "oklch(0.985 0 0)", "--card": "oklch(0.205 0 0)", "--card-foreground": "oklch(0.985 0 0)",
    "--popover": "oklch(0.205 0 0)", "--popover-foreground": "oklch(0.985 0 0)", "--primary": "oklch(0.87 0 0)", "--primary-foreground": "oklch(0.205 0 0)",
    "--secondary": "oklch(0.269 0 0)", "--secondary-foreground": "oklch(0.985 0 0)", "--muted": "oklch(0.205 0 0)", "--muted-foreground": "oklch(0.708 0 0)",
    "--accent": "oklch(0.371 0 0)", "--accent-foreground": "oklch(0.985 0 0)", "--destructive": "oklch(0.704 0.191 22.216)", "--border": "oklch(1 0 0 / 10%)",
    "--input": "oklch(1 0 0 / 15%)", "--ring": "oklch(0.556 0 0)",
  },
} as const

export function generateStaticThemeCss() {
  const rules: string[] = ["/* Generated by src/theme/static-css.ts. Do not edit directly. */"]
  for (const [id, scheme] of Object.entries(colorSchemes)) {
    const root = selector("color", id)
    for (const [modeName, dark] of [["light", false], ["dark", true]] as const) {
      const mode = scheme[modeName]
      const values: Record<string, string> = { ...semantic(id, mode, dark), ...(id === "monochrome" ? exactMonochrome[modeName] : {}) }
      for (const shade of shades) {
        values[`--siab-neutral-${shade}`] = mode.neutral[shade]!
        values[`--siab-accent-${shade}`] = mode.accent[shade]!
        values[`--provider-accent-${shade}`] = mode.accent[shade]!
        if (mode.accentSecondary) {
          values[`--siab-accent-secondary-${shade}`] = mode.accentSecondary[shade]!
          values[`--provider-accent-secondary-${shade}`] = mode.accentSecondary[shade]!
        }
      }
      values["--chart-1"] = dark ? mode.accent[500] : mode.accent[600]
      values["--chart-2"] = dark ? "#34d399" : "#059669"
      values["--chart-3"] = dark ? "#fbbf24" : "#d97706"
      values["--chart-4"] = dark ? "#f87171" : "#dc2626"
      values["--chart-5"] = dark ? "#a78bfa" : "#7c3aed"
      // Adapted form controls use this semantic surface in place of the
      // upstream `bg-white dark:bg-background` pair. It is valid for the
      // exact monochrome reference as well as every tinted tenant preset.
      values["--provider-surface"] = "var(--background)"
      if (id !== "monochrome") {
        values["--provider-grid-line"] = `oklch(0.55 0.012 ${hues[id]} / 18%)`
        values["--provider-grid-dot"] = `oklch(0.55 0.012 ${hues[id]} / 24%)`
      }
      const modeSelector = dark ? `${root}[data-rt-mode="dark"],html[data-siab-color-mode="dark"] ${root}` : `${root}:not([data-rt-mode="dark"])`
      rules.push(`${modeSelector}{${declarations(values)};color-scheme:${modeName};background-color:var(--background);color:var(--foreground)}`)
    }
  }
  for (const [id, font] of Object.entries(fontSchemes)) {
    rules.push(`${selector("font", id)}{${declarations({
      "--siab-font-display": font.roles.display,
      "--siab-font-heading": font.roles.heading,
      "--siab-font-body": font.roles.body,
      "--siab-font-mono": font.roles.mono,
      "--font-title": "var(--siab-font-display)", "--font-heading": "var(--siab-font-heading)", "--font-text": "var(--siab-font-body)",
      "--font-sans": "var(--siab-font-body)", "--font-inter": "var(--siab-font-body)", "--font-geist": "var(--siab-font-body)", "--font-satoshi": "var(--siab-font-body)",
      "--font-serif": "var(--siab-font-heading)", "--font-mono": "var(--siab-font-mono)",
    })}}`)
  }
  for (const [id, shape] of Object.entries(shapeSchemes)) {
    const radius = shape.radius
    rules.push(`${selector("shape", id)}{${declarations({
      "--radius": radius.lg, "--siab-radius-control": id === "rounded" ? radius.full : radius.lg,
      "--radius-sm": radius.sm, "--radius-md": radius.md, "--radius-lg": radius.lg, "--radius-xl": radius.xl,
      "--radius-2xl": radius["2xl"], "--radius-3xl": radius["3xl"], "--radius-4xl": radius["4xl"], "--radius-full": radius.full,
      "--siab-radius-none": radius.none, "--siab-radius-sm": radius.sm, "--siab-radius-md": radius.md, "--siab-radius-lg": radius.lg,
      "--siab-radius-xl": radius.xl, "--siab-radius-2xl": radius["2xl"], "--siab-radius-3xl": radius["3xl"], "--siab-radius-4xl": radius["4xl"], "--siab-radius-full": radius.full,
      "--provider-radius-hero-gradient": radius.xl,
    })}}`)
  }
  const themedPalettes: Record<string, string> = {}
  for (const shade of shades) {
    for (const family of ["slate", "gray", "zinc", "neutral", "stone"]) themedPalettes[`--color-${family}-${shade}`] = `var(--siab-neutral-${shade})`
    for (const family of ["sky", "blue", "indigo", "violet", "purple", "fuchsia", "pink", "rose", "cyan", "teal"]) themedPalettes[`--color-${family}-${shade}`] = `var(--siab-accent-${shade})`
  }
  rules.push(`:where(.rt-canvas,[data-siab-theme-scope])[data-theme-color]:not([data-theme-color="monochrome"]){${declarations(themedPalettes)}}`)
  return `${rules.join("\n")}\n`
}
