import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"
import { CTA } from "@/blocks/CTA"

const read = (path: string) => readFileSync(path, "utf8")

describe("CTA quote background image contract", () => {
  it("stores and exposes an editable CTA background media field", () => {
    const block = read("src/blocks/CTA.ts")
    const canvas = read("src/components/editor/canvas/blocks/CTA.tsx")
    const inlineImage = read("src/components/editor/canvas/inline/InlineImage.tsx")

    expect(block).toContain('name: "backgroundImage"')
    expect(block).toContain('type: "upload"')
    expect(block).toContain('relationTo: "media"')
    expect(canvas).toContain("value={block.backgroundImage}")
    expect(canvas).toContain('onChange={set("backgroundImage")}')
    expect(canvas).toContain('field: "backgroundImage"')
    expect(canvas).toContain('chrome="overlay"')
    expect(canvas).toContain('emptyLabel={t("addBackgroundImage")}')
    expect(canvas).toContain('changeLabel={t("changeBackgroundImage")}')
    expect(canvas).toContain('removeLabel={t("removeBackgroundImage")}')
    expect(canvas).toContain("openOnImageClick={false}")
    expect(canvas).toContain("const contactCta = block.primary?.href?.trim() ? block.primary : block.secondary")
    expect(canvas).toContain("const setContactCta = (value: any) => onUpdate({ ...block, primary: value, secondary: null })")
    expect(canvas).toContain("value={contactCta}")
    expect(canvas).toContain("onChange={setContactCta}")
    expect(canvas).toContain('emptyLabel={t("addContactLink")}')
    expect(canvas).toContain('emptyLabel={t("addCtaButton")}')
    expect(canvas).not.toContain('emptyLabel={`+ ${t("addContactLink")}`}')
    expect(canvas).not.toContain('emptyLabel={`+ ${t("addCtaButton")}`}')
    expect(canvas).not.toContain("emptyClassName=")
    expect(inlineImage).toContain("openOnImageClick?: boolean")
    expect(inlineImage).toContain("openOnImageClick = true")
    expect(inlineImage).toContain("const handleSurfaceClick")
    expect(inlineImage).toContain("const handleChromeClick")
    expect(inlineImage).toContain("if (!openOnImageClick) return")
    expect(inlineImage).toContain("const isCustomerPreview = isCustomerPreviewView(view)")
    expect(inlineImage).toContain("const surfaceIsEditable = !isCustomerPreview && (openOnImageClick || isReadOnly)")
    expect(inlineImage).toContain("const showHoverOverlayChrome = !isCustomerPreview && showOverlayChrome")
    expect(inlineImage).toContain("onClick={surfaceIsEditable ? handleSurfaceClick : undefined}")
    expect(inlineImage).toContain("onClick={handleChromeClick}")
    expect(inlineImage).toContain('data-siab-canvas-chrome="inline-image"')
    expect(inlineImage).toContain("createPortal(")
    expect(inlineImage).toContain("useCanvasChromeVisibility")
    expect(inlineImage).toContain("showHoverOverlayChrome")
    expect(inlineImage).toContain("useFixedAnchorRect(chromeAnchorNode, showHoverOverlayChrome)")
    expect(inlineImage).toContain("node.isConnected")
    expect(inlineImage).toContain('useCspStyleRule(')
    expect(inlineImage).toContain('"inline-image-chrome"')
    expect(inlineImage).toContain("left:${formatCssPx(Math.max(8, chromeRect.left + 8))}")
    expect(inlineImage).toContain("top:${formatCssPx(Math.max(8, chromeRect.top + 8))}")
    expect(inlineImage).toContain("{overlayPosition.styleElement}")
    expect(inlineImage).toContain("${overlayPosition.className} fixed z-[19]")
    expect(inlineImage).toContain('className="pointer-events-none absolute inset-0 z-10 block"')
    expect(inlineImage).not.toContain('className={["rt-click-edit cursor-pointer", backgroundStyle.className')
    expect(inlineImage).toContain("showDefaultChrome")
    expect(inlineImage).toContain("Pencil")
    expect(inlineImage).toContain('size="icon-sm"')
    expect(inlineImage).toContain("Trash2")
    expect(inlineImage).toContain("onChange(null)")
  })

  it("keeps CTA links optional while exposing primary for manifest/sidebar editing", () => {
    const canvas = read("src/components/editor/canvas/blocks/CTA.tsx")
    const elements = read("src/components/editor/canvas/blockElements.ts")
    const primary = (CTA.fields as any[]).find((field) => field.name === "primary")
    const primaryLabel = primary.fields.find((field: any) => field.name === "label")
    const primaryHref = primary.fields.find((field: any) => field.name === "href")

    expect(primaryLabel.required).toBeUndefined()
    expect(primaryHref.required).toBeUndefined()
    expect(canvas).toContain('field: "primary"')
    expect(elements).toContain("isLinkGroup")
  })

  it("does not request the old missing hardcoded bedroom image in the CMS canvas", () => {
    const canvas = read("src/components/editor/canvas/blocks/CTA.tsx")

    expect(canvas).not.toContain("/media/bedroom.jpg")
  })
})
