import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const read = (path: string) => readFileSync(path, "utf8")

describe("page-editor theme toolbar", () => {
  it("exposes color, font, shape and Hero 01 background controls", () => {
    const themeBar = read("src/components/editor/theme/editor-theme-toolbar.tsx")
    const radiusControl = read("src/components/editor/theme/radius-control.tsx")
    const pageForm = read("src/components/forms/PageForm.tsx")

    expect(themeBar).toContain('type Segment = "colors" | "fonts" | "shape" | "backgroundMode"')
    expect(themeBar).toContain("BackgroundModeControl")
    expect(themeBar).not.toContain("DensityControl")
    expect(themeBar).not.toContain("densityLevels")
    expect(themeBar).not.toContain("stylePresetLevels")
    expect(pageForm).not.toContain("DENSITY_PRESETS")
    expect(pageForm).not.toContain("stylePresetLevels={STYLE_PRESETS}")
    expect(radiusControl).toContain("export const ShapeControl")
    expect(radiusControl).not.toContain("export const DensityControl")
    expect(radiusControl).toContain("shapeId")
    expect(radiusControl).not.toContain("densityId")
  })

  it("uses functional theme updates so quick toolbar patches merge with the latest state", () => {
    const themeBar = read("src/components/editor/theme/editor-theme-toolbar.tsx")

    expect(themeBar).toContain("React.Dispatch<React.SetStateAction<ThemeTokens | null>>")
    expect(themeBar).toContain("onThemeChange((current) => mergeThemePatch")
  })

  it("renders mobile shuffle/default controls from approved theme presets only", () => {
    const themeBar = read("src/components/editor/theme/editor-theme-toolbar.tsx")

    expect(themeBar).toContain("DEFAULT_THEME_TOKEN_SPEC")
    expect(themeBar).toContain("MOBILE_RANDOM_MODES")
    expect(themeBar).toContain("pickRandom(palettes)")
    expect(themeBar).toContain("pickRandom(fonts)")
    expect(themeBar).toContain("pickRandom(radiusLevels ?? [])")
    expect(themeBar).not.toContain("densityLevels")
    expect(themeBar).toContain('className="flex justify-center py-2 md:hidden"')
    expect(themeBar).toContain("<Dices")
    expect(themeBar).toContain("<RotateCcw")
    expect(themeBar).toContain('t("shuffle")')
    expect(themeBar).toContain('t("default")')
    expect(themeBar).toContain('className="hidden md:block"')
    expect(themeBar).not.toContain('size="lg"')
    expect(themeBar).toContain("onClick={() => setOpenSegment((current) => (current === segment ? null : segment))}")
    expect(themeBar).toContain("onPointerDownOutside={() => setOpenSegment(null)}")
    expect(themeBar).toContain("onFocusOutside={() => setOpenSegment(null)}")
  })

  it("hosts site-wide token-bridge controls in the inspector site-look panel", () => {
    const panel = read("src/components/editor/theme/site-appearance-panel.tsx")

    expect(panel).toContain("export function SiteAppearancePanel")
    expect(panel).toContain("data-siab-site-look")
    expect(panel).toContain("mergeThemePatch")
    expect(panel).toContain("PalettePicker")
    expect(panel).toContain("FontPicker")
    expect(panel).toContain("ShapeControl")
    expect(panel).toContain("BackgroundModeControl")
    expect(panel).toContain("SITE_LOOK_RANDOM_MODES")
    expect(panel).toContain("normalizeThemeForSave(DEFAULT_THEME_TOKEN_SPEC)")
    expect(panel).toContain('layout="settings"')
    expect(panel).toContain("rounded-md border border-border bg-card p-4")
    expect(panel).toContain("t(\"colourPalette\")")
    expect(panel).toContain("t(\"fontPairings\")")
    expect(panel).toContain("t(\"cornerRadius\")")
    expect(panel).toContain("site-look-dark-mode")
    expect(panel).not.toContain('layout="mobile"')
    expect(panel).not.toContain("w-[14rem]")
    expect(panel).not.toContain("DensityControl")
    expect(read("src/components/editor/theme/palette-picker.tsx")).toContain('"settings"')
    expect(read("src/components/editor/theme/font-picker.tsx")).toContain('"settings"')
    expect(read("src/components/editor/theme/radius-control.tsx")).toContain('"settings"')
    expect(read("src/components/editor/theme/background-mode-control.tsx")).toContain('"settings"')
  })

  it("mounts and centers the page-editor toolbar over the canvas column only", () => {
    const pageForm = read("src/components/forms/PageForm.tsx")

    expect(pageForm).toContain("{!readOnly && isDesktop && (")
    expect(pageForm).toContain("EditorThemeToolbar")
    expect(pageForm).toContain("preview={pageEditorFrame}")
    expect(pageForm).toContain("SiteAppearancePanel")
    expect(pageForm).toContain('className="pointer-events-none sticky top-[7.5rem] z-20 grid w-full grid-cols-[minmax(0,1fr)_360px] gap-3"')
    expect(pageForm).toContain('className="pointer-events-auto flex justify-center"')
    expect(pageForm).not.toContain("SegmentedPill")
    expect(pageForm).not.toContain("FLOATING_PILL_CLASS")
    expect(pageForm).not.toContain('className={`sticky z-20 flex justify-center pointer-events-none ${isDesktop ? "top-[6.5rem]" : "top-0"}`}')
  })

  it("uses the shared neo tray without a second pill style", () => {
    const themeBar = read("src/components/editor/theme/editor-theme-toolbar.tsx")
    const floatingPill = read("src/components/editor/floating-pill.ts")
    const navigation = read("src/components/navigation/NavigationManager.tsx")
    const settings = read("src/components/forms/SettingsForm.tsx")
    const desktopPreview = read("src/components/preview/preview-desktop-theme-toolbar.tsx")
    const mobilePreview = read("src/components/preview/preview-mobile-theme-bar.tsx")
    const mobileFloatingPill = read("src/components/common/mobile-floating-pill.tsx")
    const retro = read("../../packages/ui/src/lib/retro.ts")
    const tokens = read("../../packages/ui/src/styles/shadcn.css")
    const toggle = read("../../packages/ui/src/components/toggle.tsx")

    expect(retro).toContain("hover:shadow-shadow-hover")
    expect(retro).toContain("duration-200")
    expect(retro).toContain("transition-[translate,transform,box-shadow,background-color,color]")
    expect(tokens).toContain("--radius-base: 0px")
    expect(tokens).toContain("--main: #f5e900")
    expect(retro).toContain("siab-neo-tray")
    expect(retro).toContain("in-[.siab-neo-tray]:shadow-none")
    expect(tokens).toContain("--shadow-shadow: 5px 5px 0px 0px var(--neo-slab)")
    expect(tokens).toContain("--shadow-shadow-hover: 3px 3px 0px 0px var(--neo-slab)")
    expect(tokens).not.toContain("--shadow-shadow-accent")
    expect(tokens).not.toContain("--shadow-shadow-inverse")
    expect(retro).toContain("neoPress")
    expect(retro).toContain("shadow-shadow")
    expect(retro).toContain("neoField")
    expect(retro).not.toContain("neoPressAccent")
    expect(retro).not.toContain("neoPressInk")
    expect(toggle).not.toContain("transition-all")
    expect(floatingPill).toContain("neoTray")
    expect(floatingPill).toContain("p-1.5")
    expect(floatingPill).not.toContain("backdrop-blur")
    expect(floatingPill).not.toContain("rounded-lg")
    expect(themeBar).toContain('className={cn(FLOATING_PILL_CLASS, "inline-flex")}')
    expect(themeBar).not.toContain("bg-muted/30")
    expect(themeBar).not.toContain("backdrop-blur")
    expect(themeBar).toContain('variant={openSegment === segment ? "default" : "outline"}')
    expect(navigation).toContain("<SegmentedPill<NavZone>")
    expect(navigation).not.toContain("FLOATING_PILL_CLASS")
    expect(settings).toContain("<SegmentedPill<SectionKey>")
    expect(settings).not.toContain("FLOATING_PILL_CLASS")
    expect(desktopPreview).not.toContain("FLOATING_PILL_CLASS")
    expect(mobilePreview).not.toContain("FLOATING_PILL_CLASS")
    expect(mobileFloatingPill).not.toContain("FLOATING_PILL_CLASS")
  })
})
