import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const read = (path: string) => readFileSync(path, "utf8")

describe("mobile inspector snap contract", () => {
  it("collapses to a handle by default and ignores invalid vaul snap callbacks", () => {
    const inspectorBar = read("src/components/editor/mobile/mobile-inspector-bar.tsx")

    expect(inspectorBar).toContain("MOBILE_INSPECTOR_COLLAPSED_SNAP")
    expect(inspectorBar).toContain("const SNAP_POINTS: MobileSnap[] = [MOBILE_INSPECTOR_COLLAPSED_SNAP, 0.42, 0.92]")
    expect(inspectorBar).toContain("const isMobileSnap = (snap: unknown): snap is MobileSnap")
    expect(inspectorBar).toContain("if (!isMobileSnap(snap)) return")
    expect(inspectorBar).toContain("if (snap === MOBILE_INSPECTOR_COLLAPSED_SNAP)")
    expect(inspectorBar).toContain('if (isIdle) setSelected({ blockIndex, field: "" })')
    expect(inspectorBar).toContain("expandTo(snap)")
    expect(inspectorBar).toContain("dismissible={false}")
    expect(inspectorBar).not.toContain("?? 0.42")
  })

  it("ships vaul snap mechanics through nonce-bearing css for production CSP", () => {
    const sharedCss = read("src/components/editor/mobile/vaulBottomSnapCss.ts")
    const inspectorBar = read("src/components/editor/mobile/mobile-inspector-bar.tsx")

    expect(inspectorBar).toContain('import { useCspNonce } from "@siteinabox/ui/lib/csp-nonce"')
    expect(sharedCss).toContain("export const VAUL_BOTTOM_SNAP_CSS = `")
    expect(sharedCss).toContain('[data-vaul-drawer][data-vaul-snap-points="true"][data-vaul-drawer-direction="bottom"]')
    expect(sharedCss).toContain('[data-vaul-drawer][data-vaul-delayed-snap-points="true"][data-vaul-drawer-direction="bottom"]')
    expect(sharedCss).toContain("[data-vaul-handle] {")
    expect(sharedCss).toContain("height: 0.375rem;")
    expect(sharedCss).toContain("width: 2.5rem;")
    expect(inspectorBar).toContain("nonce={cspNonce}")
    expect(inspectorBar).toContain("data-mobile-inspector-vaul-css")
  })

  it("promotes to the editing detent only for intentional editable-field focus", () => {
    const sharedCss = read("src/components/editor/mobile/vaulBottomSnapCss.ts")
    const inspectorBar = read("src/components/editor/mobile/mobile-inspector-bar.tsx")
    const componentEditor = read("src/components/editor/mobile/mobile-component-editor.tsx")

    expect(inspectorBar).toContain("handleOnly")
    expect(inspectorBar).toContain("only the visible grip drags the sheet")
    expect(sharedCss).toContain("touch-action: auto;")
    expect(sharedCss).toContain("touch-action: none;")
    expect(componentEditor).toContain('import { Drawer as Vaul } from "vaul"')
    expect(componentEditor).toContain("<Vaul.Close asChild>")
    expect(componentEditor).toContain("data-mobile-editor-close")
    expect(componentEditor).toContain("size-10 rounded-none")
    expect(componentEditor).toContain("onClick={handleCloseClick}")
    expect(componentEditor).not.toContain("const handleCloseTouchEnd")
    expect(componentEditor).not.toContain("onTouchEnd={handleCloseTouchEnd}")
    expect(componentEditor).not.toContain("data-vaul-no-drag")
    expect(componentEditor).toContain("function getEditableFocusTarget")
    expect(componentEditor).toContain("onPointerDownCapture={onEditorPointerDown}")
    expect(componentEditor).toContain("onFocusCapture={onEditorFocus}")
    expect(componentEditor).toContain("requestAnimationFrame")
    expect(componentEditor).toContain("if (!getEditableFocusTarget(event.target)) return")
    expect(componentEditor).toContain("if (!focusReadyRef.current && !hasRecentEditablePointer) return")
    expect(componentEditor).not.toContain("onFocusCapture={() => focusPop()}")
  })

  it("uses a three-pane page editor with a bottom action bar", () => {
    const shell = read("src/components/editor/iframe/MobilePageEditorShell.tsx")
    const floatingPill = read("src/components/common/mobile-floating-pill.tsx")

    expect(shell).toContain("data-siab-mobile-page-editor")
    expect(shell).toContain("data-siab-editor-pager")
    expect(shell).toContain("data-mobile-page-editor-bar")
    expect(shell).toContain("<SaveButton")
    expect(shell).toContain('scrollToPane("agent")')
    expect(shell).toContain('scrollToPane("preview")')
    expect(shell).toContain('scrollToPane("inspector")')
    expect(shell).toContain('aria-label={t("exitEditor")}')
    expect(shell).toContain('size="icon"')
    expect(shell).not.toContain("togglePane")
    expect(shell).toContain('if (changed && pane === "preview") scrollToPane("inspector")')
    expect(shell).not.toContain("MobileBackPill")
    expect(shell).not.toContain("data-mobile-trash-pill")
    expect(floatingPill).toContain("bg-success text-success-foreground")
    expect(floatingPill).toContain("visible = true")
    expect(floatingPill).toContain('? "translate-x-[3.75rem]"')
    expect(floatingPill).toContain("pointer-events-auto opacity-100 scale-100 translate-x-0")
    expect(floatingPill).toContain("!isInteractive && \"pointer-events-none\"")
    expect(floatingPill).not.toContain("opacity-50")
    expect(floatingPill).toContain('dataAttrs?.["data-mobile-trash-pill"] != null ? "z-40" : "z-50"')
    expect(floatingPill).not.toContain("animate-pulse")
    expect(floatingPill).not.toContain("ring-offset-background")
  })

  it("opens image selection directly on mobile and uses a thumb-sized media close control", () => {
    const componentEditor = read("src/components/editor/mobile/mobile-component-editor.tsx")
    const inspectorBar = read("src/components/editor/mobile/mobile-inspector-bar.tsx")
    const mediaSheet = read("src/components/editor/mobile/mobile-media-sheet.tsx")
    const blockFields = read("src/components/editor/fields/block-form-fields.tsx")

    expect(inspectorBar).toContain('import { useFormContext } from "react-hook-form"')
    expect(inspectorBar).toContain('import { MobileMediaSheet } from "@/components/editor/mobile/mobile-media-sheet"')
    expect(inspectorBar).toContain("const isDirectMediaSelection = state.selected != null && selectedName != null && selectedSpec?.kind === \"image\"")
    expect(inspectorBar).toContain("if (isDirectMediaSelection)")
    expect(inspectorBar).toContain("useInspectorKeyboardLock(!isIdle && !isDirectMediaSelection)")
    expect(inspectorBar).toContain("if (isIdle || isDirectMediaSelection) return")
    expect(inspectorBar).toContain("setValue(selectedName, media, { shouldDirty: true })")
    expect(inspectorBar).toContain("function resolveSelectedSpec")
    expect(componentEditor).not.toContain("const didAutoOpenRef = React.useRef(false)")
    expect(mediaSheet).toContain("showCloseButton={false}")
    expect(mediaSheet).toContain("<SheetClose asChild>")
    expect(mediaSheet).toContain('className="size-10 rounded-none border border-border bg-muted text-foreground shadow-sm hover:bg-accent hover:text-accent-foreground"')
    expect(mediaSheet).toContain("<X className=\"size-4\"")
    expect(mediaSheet).toContain("data-mobile-media-close")
    expect(blockFields).toContain('import { MediaPicker } from "@/components/media/MediaPicker"')
    expect(blockFields).not.toContain("InlineImage")
  })
})
