// Generated by scripts/import-shadcnui-blocks.mjs. Do not edit by hand.
import * as React from "react"
import type { Block } from "@siteinabox/contracts"
import type { BlockRenderOptions } from "../../blocks/types"
import View001 from "./variants/blog-01/view"
import { adaptVariant as adapt001 } from "./variants/blog-01/adapter"
import View002 from "./variants/blog-02/view"
import { adaptVariant as adapt002 } from "./variants/blog-02/adapter"
import View003 from "./variants/blog-03/view"
import { adaptVariant as adapt003 } from "./variants/blog-03/adapter"
import View004 from "./variants/contact-01/view"
import { adaptVariant as adapt004 } from "./variants/contact-01/adapter"
import View005 from "./variants/contact-02/view"
import { adaptVariant as adapt005 } from "./variants/contact-02/adapter"
import View006 from "./variants/contact-03/view"
import { adaptVariant as adapt006 } from "./variants/contact-03/adapter"
import View007 from "./variants/faq-01/view"
import { adaptVariant as adapt007 } from "./variants/faq-01/adapter"
import View008 from "./variants/faq-02/view"
import { adaptVariant as adapt008 } from "./variants/faq-02/adapter"
import View009 from "./variants/faq-03/view"
import { adaptVariant as adapt009 } from "./variants/faq-03/adapter"
import View010 from "./variants/faq-04/view"
import { adaptVariant as adapt010 } from "./variants/faq-04/adapter"
import View011 from "./variants/faq-05/view"
import { adaptVariant as adapt011 } from "./variants/faq-05/adapter"
import View012 from "./variants/faq-06/view"
import { adaptVariant as adapt012 } from "./variants/faq-06/adapter"
import View013 from "./variants/faq-07/view"
import { adaptVariant as adapt013 } from "./variants/faq-07/adapter"
import View014 from "./variants/features-01/view"
import { adaptVariant as adapt014 } from "./variants/features-01/adapter"
import View015 from "./variants/features-02/view"
import { adaptVariant as adapt015 } from "./variants/features-02/adapter"
import View016 from "./variants/features-03/view"
import { adaptVariant as adapt016 } from "./variants/features-03/adapter"
import View017 from "./variants/features-04/view"
import { adaptVariant as adapt017 } from "./variants/features-04/adapter"
import View018 from "./variants/features-05/view"
import { adaptVariant as adapt018 } from "./variants/features-05/adapter"
import View019 from "./variants/features-06/view"
import { adaptVariant as adapt019 } from "./variants/features-06/adapter"
import View020 from "./variants/features-07/view"
import { adaptVariant as adapt020 } from "./variants/features-07/adapter"
import View021 from "./variants/hero-01/view"
import { adaptVariant as adapt021 } from "./variants/hero-01/adapter"
import View022 from "./variants/hero-02/view"
import { adaptVariant as adapt022 } from "./variants/hero-02/adapter"
import View023 from "./variants/hero-03/view"
import { adaptVariant as adapt023 } from "./variants/hero-03/adapter"
import View024 from "./variants/hero-04/view"
import { adaptVariant as adapt024 } from "./variants/hero-04/adapter"
import View025 from "./variants/hero-05/view"
import { adaptVariant as adapt025 } from "./variants/hero-05/adapter"
import View026 from "./variants/hero-06/view"
import { adaptVariant as adapt026 } from "./variants/hero-06/adapter"
import View027 from "./variants/hero-07/view"
import { adaptVariant as adapt027 } from "./variants/hero-07/adapter"
import View028 from "./variants/logo-cloud-01/view"
import { adaptVariant as adapt028 } from "./variants/logo-cloud-01/adapter"
import View029 from "./variants/logo-cloud-02/view"
import { adaptVariant as adapt029 } from "./variants/logo-cloud-02/adapter"
import View030 from "./variants/logo-cloud-03/view"
import { adaptVariant as adapt030 } from "./variants/logo-cloud-03/adapter"
import View031 from "./variants/logo-cloud-04/view"
import { adaptVariant as adapt031 } from "./variants/logo-cloud-04/adapter"
import View032 from "./variants/logo-cloud-05/view"
import { adaptVariant as adapt032 } from "./variants/logo-cloud-05/adapter"
import View033 from "./variants/logo-cloud-06/view"
import { adaptVariant as adapt033 } from "./variants/logo-cloud-06/adapter"
import View034 from "./variants/logo-cloud-07/view"
import { adaptVariant as adapt034 } from "./variants/logo-cloud-07/adapter"
import View035 from "./variants/pricing-01/view"
import { adaptVariant as adapt035 } from "./variants/pricing-01/adapter"
import View036 from "./variants/pricing-02/view"
import { adaptVariant as adapt036 } from "./variants/pricing-02/adapter"
import View037 from "./variants/pricing-03/view"
import { adaptVariant as adapt037 } from "./variants/pricing-03/adapter"
import View038 from "./variants/pricing-04/view"
import { adaptVariant as adapt038 } from "./variants/pricing-04/adapter"
import View039 from "./variants/pricing-05/view"
import { adaptVariant as adapt039 } from "./variants/pricing-05/adapter"
import View040 from "./variants/pricing-06/view"
import { adaptVariant as adapt040 } from "./variants/pricing-06/adapter"
import View041 from "./variants/stats-01/view"
import { adaptVariant as adapt041 } from "./variants/stats-01/adapter"
import View042 from "./variants/stats-02/view"
import { adaptVariant as adapt042 } from "./variants/stats-02/adapter"
import View043 from "./variants/team-01/view"
import { adaptVariant as adapt043 } from "./variants/team-01/adapter"
import View044 from "./variants/team-02/view"
import { adaptVariant as adapt044 } from "./variants/team-02/adapter"
import View045 from "./variants/team-03/view"
import { adaptVariant as adapt045 } from "./variants/team-03/adapter"
import View046 from "./variants/team-04/view"
import { adaptVariant as adapt046 } from "./variants/team-04/adapter"
import View047 from "./variants/team-05/view"
import { adaptVariant as adapt047 } from "./variants/team-05/adapter"
import View048 from "./variants/testimonials-01/view"
import { adaptVariant as adapt048 } from "./variants/testimonials-01/adapter"
import View049 from "./variants/testimonials-02/view"
import { adaptVariant as adapt049 } from "./variants/testimonials-02/adapter"
import View050 from "./variants/testimonials-03/view"
import { adaptVariant as adapt050 } from "./variants/testimonials-03/adapter"
import View051 from "./variants/testimonials-04/view"
import { adaptVariant as adapt051 } from "./variants/testimonials-04/adapter"
import View052 from "./variants/testimonials-05/view"
import { adaptVariant as adapt052 } from "./variants/testimonials-05/adapter"
import View053 from "./variants/testimonials-06/view"
import { adaptVariant as adapt053 } from "./variants/testimonials-06/adapter"
import View054 from "./variants/timeline-01/view"
import { adaptVariant as adapt054 } from "./variants/timeline-01/adapter"
import View055 from "./variants/timeline-02/view"
import { adaptVariant as adapt055 } from "./variants/timeline-02/adapter"
import View056 from "./variants/timeline-03/view"
import { adaptVariant as adapt056 } from "./variants/timeline-03/adapter"
import View057 from "./variants/timeline-04/view"
import { adaptVariant as adapt057 } from "./variants/timeline-04/adapter"
import View058 from "./variants/timeline-05/view"
import { adaptVariant as adapt058 } from "./variants/timeline-05/adapter"
import View059 from "./variants/timeline-06/view"
import { adaptVariant as adapt059 } from "./variants/timeline-06/adapter"
import View060 from "./variants/timeline-07/view"
import { adaptVariant as adapt060 } from "./variants/timeline-07/adapter"
import View061 from "./variants/cta-01/view"
import { adaptVariant as adapt061 } from "./variants/cta-01/adapter"
import View062 from "./variants/cta-02/view"
import { adaptVariant as adapt062 } from "./variants/cta-02/adapter"
import View063 from "./variants/cta-03/view"
import { adaptVariant as adapt063 } from "./variants/cta-03/adapter"
import View064 from "./variants/cta-04/view"
import { adaptVariant as adapt064 } from "./variants/cta-04/adapter"
import View065 from "./variants/cta-05/view"
import { adaptVariant as adapt065 } from "./variants/cta-05/adapter"
import View066 from "./variants/cta-06/view"
import { adaptVariant as adapt066 } from "./variants/cta-06/adapter"
import View067 from "./variants/cta-07/view"
import { adaptVariant as adapt067 } from "./variants/cta-07/adapter"
import View068 from "./variants/carousel-block-01/view"
import { adaptVariant as adapt068 } from "./variants/carousel-block-01/adapter"
import View069 from "./variants/carousel-block-02/view"
import { adaptVariant as adapt069 } from "./variants/carousel-block-02/adapter"
import View070 from "./variants/hero-08/view"
import { adaptVariant as adapt070 } from "./variants/hero-08/adapter"
import View071 from "./variants/features-08/view"
import { adaptVariant as adapt071 } from "./variants/features-08/adapter"
import View072 from "./variants/features-09/view"
import { adaptVariant as adapt072 } from "./variants/features-09/adapter"
import View073 from "./variants/features-10/view"
import { adaptVariant as adapt073 } from "./variants/features-10/adapter"
import View074 from "./variants/features-11/view"
import { adaptVariant as adapt074 } from "./variants/features-11/adapter"
import View075 from "./variants/features-12/view"
import { adaptVariant as adapt075 } from "./variants/features-12/adapter"
import View076 from "./variants/features-13/view"
import { adaptVariant as adapt076 } from "./variants/features-13/adapter"
import View077 from "./variants/features-14/view"
import { adaptVariant as adapt077 } from "./variants/features-14/adapter"
import View078 from "./variants/features-15/view"
import { adaptVariant as adapt078 } from "./variants/features-15/adapter"
import View079 from "./variants/features-16/view"
import { adaptVariant as adapt079 } from "./variants/features-16/adapter"
import View080 from "./variants/features-17/view"
import { adaptVariant as adapt080 } from "./variants/features-17/adapter"
import View081 from "./variants/features-18/view"
import { adaptVariant as adapt081 } from "./variants/features-18/adapter"
import View082 from "./variants/faq-08/view"
import { adaptVariant as adapt082 } from "./variants/faq-08/adapter"
import View083 from "./variants/faq-09/view"
import { adaptVariant as adapt083 } from "./variants/faq-09/adapter"
import View084 from "./variants/faq-10/view"
import { adaptVariant as adapt084 } from "./variants/faq-10/adapter"
import View085 from "./variants/faq-11/view"
import { adaptVariant as adapt085 } from "./variants/faq-11/adapter"
import View086 from "./variants/faq-12/view"
import { adaptVariant as adapt086 } from "./variants/faq-12/adapter"
import View087 from "./variants/faq-13/view"
import { adaptVariant as adapt087 } from "./variants/faq-13/adapter"
import View088 from "./variants/faq-14/view"
import { adaptVariant as adapt088 } from "./variants/faq-14/adapter"
import View089 from "./variants/logo-cloud-08/view"
import { adaptVariant as adapt089 } from "./variants/logo-cloud-08/adapter"
import View090 from "./variants/logo-cloud-09/view"
import { adaptVariant as adapt090 } from "./variants/logo-cloud-09/adapter"
import View091 from "./variants/logo-cloud-10/view"
import { adaptVariant as adapt091 } from "./variants/logo-cloud-10/adapter"
import View092 from "./variants/logo-cloud-11/view"
import { adaptVariant as adapt092 } from "./variants/logo-cloud-11/adapter"
import View093 from "./variants/logo-cloud-12/view"
import { adaptVariant as adapt093 } from "./variants/logo-cloud-12/adapter"
import View094 from "./variants/logo-cloud-13/view"
import { adaptVariant as adapt094 } from "./variants/logo-cloud-13/adapter"
import View095 from "./variants/logo-cloud-14/view"
import { adaptVariant as adapt095 } from "./variants/logo-cloud-14/adapter"
import View096 from "./variants/logo-cloud-15/view"
import { adaptVariant as adapt096 } from "./variants/logo-cloud-15/adapter"
import View097 from "./variants/pricing-07/view"
import { adaptVariant as adapt097 } from "./variants/pricing-07/adapter"
import View098 from "./variants/pricing-08/view"
import { adaptVariant as adapt098 } from "./variants/pricing-08/adapter"
import View099 from "./variants/pricing-09/view"
import { adaptVariant as adapt099 } from "./variants/pricing-09/adapter"
import View100 from "./variants/pricing-10/view"
import { adaptVariant as adapt100 } from "./variants/pricing-10/adapter"
import View101 from "./variants/stats-03/view"
import { adaptVariant as adapt101 } from "./variants/stats-03/adapter"
import View102 from "./variants/stats-04/view"
import { adaptVariant as adapt102 } from "./variants/stats-04/adapter"
import View103 from "./variants/stats-05/view"
import { adaptVariant as adapt103 } from "./variants/stats-05/adapter"
import View104 from "./variants/stats-06/view"
import { adaptVariant as adapt104 } from "./variants/stats-06/adapter"
import View105 from "./variants/stats-07/view"
import { adaptVariant as adapt105 } from "./variants/stats-07/adapter"
import View106 from "./variants/stats-08/view"
import { adaptVariant as adapt106 } from "./variants/stats-08/adapter"
import View107 from "./variants/stats-09/view"
import { adaptVariant as adapt107 } from "./variants/stats-09/adapter"
import View108 from "./variants/stats-10/view"
import { adaptVariant as adapt108 } from "./variants/stats-10/adapter"
import View109 from "./variants/stats-11/view"
import { adaptVariant as adapt109 } from "./variants/stats-11/adapter"
import View110 from "./variants/team-06/view"
import { adaptVariant as adapt110 } from "./variants/team-06/adapter"
import View111 from "./variants/team-07/view"
import { adaptVariant as adapt111 } from "./variants/team-07/adapter"
import View112 from "./variants/team-08/view"
import { adaptVariant as adapt112 } from "./variants/team-08/adapter"
import View113 from "./variants/team-09/view"
import { adaptVariant as adapt113 } from "./variants/team-09/adapter"
import View114 from "./variants/team-10/view"
import { adaptVariant as adapt114 } from "./variants/team-10/adapter"
import View115 from "./variants/team-11/view"
import { adaptVariant as adapt115 } from "./variants/team-11/adapter"
import View116 from "./variants/team-12/view"
import { adaptVariant as adapt116 } from "./variants/team-12/adapter"
import View117 from "./variants/team-13/view"
import { adaptVariant as adapt117 } from "./variants/team-13/adapter"
import View118 from "./variants/testimonials-07/view"
import { adaptVariant as adapt118 } from "./variants/testimonials-07/adapter"
import View119 from "./variants/testimonials-08/view"
import { adaptVariant as adapt119 } from "./variants/testimonials-08/adapter"
import View120 from "./variants/testimonials-09/view"
import { adaptVariant as adapt120 } from "./variants/testimonials-09/adapter"
import View121 from "./variants/testimonials-10/view"
import { adaptVariant as adapt121 } from "./variants/testimonials-10/adapter"
import View122 from "./variants/testimonials-11/view"
import { adaptVariant as adapt122 } from "./variants/testimonials-11/adapter"
import View123 from "./variants/testimonials-12/view"
import { adaptVariant as adapt123 } from "./variants/testimonials-12/adapter"
import View124 from "./variants/testimonials-13/view"
import { adaptVariant as adapt124 } from "./variants/testimonials-13/adapter"
import View125 from "./variants/blog-04/view"
import { adaptVariant as adapt125 } from "./variants/blog-04/adapter"
import View126 from "./variants/blog-05/view"
import { adaptVariant as adapt126 } from "./variants/blog-05/adapter"
import View127 from "./variants/blog-06/view"
import { adaptVariant as adapt127 } from "./variants/blog-06/adapter"
import View128 from "./variants/integrations-01/view"
import { adaptVariant as adapt128 } from "./variants/integrations-01/adapter"
import View129 from "./variants/integrations-02/view"
import { adaptVariant as adapt129 } from "./variants/integrations-02/adapter"
import View130 from "./variants/integrations-03/view"
import { adaptVariant as adapt130 } from "./variants/integrations-03/adapter"
import View131 from "./variants/integrations-04/view"
import { adaptVariant as adapt131 } from "./variants/integrations-04/adapter"
import View132 from "./variants/integrations-05/view"
import { adaptVariant as adapt132 } from "./variants/integrations-05/adapter"
const definitions = {
  "shadcnui-blocks.blog-01": { blockType: "blogCards", adapt: adapt001, View: View001 },
  "shadcnui-blocks.blog-02": { blockType: "blogCards", adapt: adapt002, View: View002 },
  "shadcnui-blocks.blog-03": { blockType: "blogCards", adapt: adapt003, View: View003 },
  "shadcnui-blocks.contact-01": { blockType: "contactSection", adapt: adapt004, View: View004 },
  "shadcnui-blocks.contact-02": { blockType: "contactSection", adapt: adapt005, View: View005 },
  "shadcnui-blocks.contact-03": { blockType: "contactSection", adapt: adapt006, View: View006 },
  "shadcnui-blocks.faq-01": { blockType: "faq", adapt: adapt007, View: View007 },
  "shadcnui-blocks.faq-02": { blockType: "faq", adapt: adapt008, View: View008 },
  "shadcnui-blocks.faq-03": { blockType: "faq", adapt: adapt009, View: View009 },
  "shadcnui-blocks.faq-04": { blockType: "faq", adapt: adapt010, View: View010 },
  "shadcnui-blocks.faq-05": { blockType: "faq", adapt: adapt011, View: View011 },
  "shadcnui-blocks.faq-06": { blockType: "faq", adapt: adapt012, View: View012 },
  "shadcnui-blocks.faq-07": { blockType: "faq", adapt: adapt013, View: View013 },
  "shadcnui-blocks.features-01": { blockType: "featureList", adapt: adapt014, View: View014 },
  "shadcnui-blocks.features-02": { blockType: "featureList", adapt: adapt015, View: View015 },
  "shadcnui-blocks.features-03": { blockType: "featureList", adapt: adapt016, View: View016 },
  "shadcnui-blocks.features-04": { blockType: "featureList", adapt: adapt017, View: View017 },
  "shadcnui-blocks.features-05": { blockType: "featureList", adapt: adapt018, View: View018 },
  "shadcnui-blocks.features-06": { blockType: "featureList", adapt: adapt019, View: View019 },
  "shadcnui-blocks.features-07": { blockType: "featureList", adapt: adapt020, View: View020 },
  "shadcnui-blocks.hero-01": { blockType: "hero", adapt: adapt021, View: View021 },
  "shadcnui-blocks.hero-02": { blockType: "hero", adapt: adapt022, View: View022 },
  "shadcnui-blocks.hero-03": { blockType: "hero", adapt: adapt023, View: View023 },
  "shadcnui-blocks.hero-04": { blockType: "hero", adapt: adapt024, View: View024 },
  "shadcnui-blocks.hero-05": { blockType: "hero", adapt: adapt025, View: View025 },
  "shadcnui-blocks.hero-06": { blockType: "hero", adapt: adapt026, View: View026 },
  "shadcnui-blocks.hero-07": { blockType: "hero", adapt: adapt027, View: View027 },
  "shadcnui-blocks.logo-cloud-01": { blockType: "logoCloud", adapt: adapt028, View: View028 },
  "shadcnui-blocks.logo-cloud-02": { blockType: "logoCloud", adapt: adapt029, View: View029 },
  "shadcnui-blocks.logo-cloud-03": { blockType: "logoCloud", adapt: adapt030, View: View030 },
  "shadcnui-blocks.logo-cloud-04": { blockType: "logoCloud", adapt: adapt031, View: View031 },
  "shadcnui-blocks.logo-cloud-05": { blockType: "logoCloud", adapt: adapt032, View: View032 },
  "shadcnui-blocks.logo-cloud-06": { blockType: "logoCloud", adapt: adapt033, View: View033 },
  "shadcnui-blocks.logo-cloud-07": { blockType: "logoCloud", adapt: adapt034, View: View034 },
  "shadcnui-blocks.pricing-01": { blockType: "pricing", adapt: adapt035, View: View035 },
  "shadcnui-blocks.pricing-02": { blockType: "pricing", adapt: adapt036, View: View036 },
  "shadcnui-blocks.pricing-03": { blockType: "pricing", adapt: adapt037, View: View037 },
  "shadcnui-blocks.pricing-04": { blockType: "pricing", adapt: adapt038, View: View038 },
  "shadcnui-blocks.pricing-05": { blockType: "pricing", adapt: adapt039, View: View039 },
  "shadcnui-blocks.pricing-06": { blockType: "pricing", adapt: adapt040, View: View040 },
  "shadcnui-blocks.stats-01": { blockType: "stats", adapt: adapt041, View: View041 },
  "shadcnui-blocks.stats-02": { blockType: "stats", adapt: adapt042, View: View042 },
  "shadcnui-blocks.team-01": { blockType: "team", adapt: adapt043, View: View043 },
  "shadcnui-blocks.team-02": { blockType: "team", adapt: adapt044, View: View044 },
  "shadcnui-blocks.team-03": { blockType: "team", adapt: adapt045, View: View045 },
  "shadcnui-blocks.team-04": { blockType: "team", adapt: adapt046, View: View046 },
  "shadcnui-blocks.team-05": { blockType: "team", adapt: adapt047, View: View047 },
  "shadcnui-blocks.testimonials-01": { blockType: "testimonials", adapt: adapt048, View: View048 },
  "shadcnui-blocks.testimonials-02": { blockType: "testimonials", adapt: adapt049, View: View049 },
  "shadcnui-blocks.testimonials-03": { blockType: "testimonials", adapt: adapt050, View: View050 },
  "shadcnui-blocks.testimonials-04": { blockType: "testimonials", adapt: adapt051, View: View051 },
  "shadcnui-blocks.testimonials-05": { blockType: "testimonials", adapt: adapt052, View: View052 },
  "shadcnui-blocks.testimonials-06": { blockType: "testimonials", adapt: adapt053, View: View053 },
  "shadcnui-blocks.timeline-01": { blockType: "contentSection", adapt: adapt054, View: View054 },
  "shadcnui-blocks.timeline-02": { blockType: "contentSection", adapt: adapt055, View: View055 },
  "shadcnui-blocks.timeline-03": { blockType: "contentSection", adapt: adapt056, View: View056 },
  "shadcnui-blocks.timeline-04": { blockType: "contentSection", adapt: adapt057, View: View057 },
  "shadcnui-blocks.timeline-05": { blockType: "contentSection", adapt: adapt058, View: View058 },
  "shadcnui-blocks.timeline-06": { blockType: "contentSection", adapt: adapt059, View: View059 },
  "shadcnui-blocks.timeline-07": { blockType: "contentSection", adapt: adapt060, View: View060 },
  "shadcnui-blocks.cta-01": { blockType: "cta", adapt: adapt061, View: View061 },
  "shadcnui-blocks.cta-02": { blockType: "cta", adapt: adapt062, View: View062 },
  "shadcnui-blocks.cta-03": { blockType: "cta", adapt: adapt063, View: View063 },
  "shadcnui-blocks.cta-04": { blockType: "cta", adapt: adapt064, View: View064 },
  "shadcnui-blocks.cta-05": { blockType: "cta", adapt: adapt065, View: View065 },
  "shadcnui-blocks.cta-06": { blockType: "cta", adapt: adapt066, View: View066 },
  "shadcnui-blocks.cta-07": { blockType: "cta", adapt: adapt067, View: View067 },
  "shadcnui-blocks.carousel-block-01": { blockType: "gallery", adapt: adapt068, View: View068 },
  "shadcnui-blocks.carousel-block-02": { blockType: "gallery", adapt: adapt069, View: View069 },
  "shadcnui-blocks.hero-08": { blockType: "hero", adapt: adapt070, View: View070 },
  "shadcnui-blocks.features-08": { blockType: "featureList", adapt: adapt071, View: View071 },
  "shadcnui-blocks.features-09": { blockType: "featureList", adapt: adapt072, View: View072 },
  "shadcnui-blocks.features-10": { blockType: "featureList", adapt: adapt073, View: View073 },
  "shadcnui-blocks.features-11": { blockType: "featureList", adapt: adapt074, View: View074 },
  "shadcnui-blocks.features-12": { blockType: "featureList", adapt: adapt075, View: View075 },
  "shadcnui-blocks.features-13": { blockType: "featureList", adapt: adapt076, View: View076 },
  "shadcnui-blocks.features-14": { blockType: "featureList", adapt: adapt077, View: View077 },
  "shadcnui-blocks.features-15": { blockType: "featureList", adapt: adapt078, View: View078 },
  "shadcnui-blocks.features-16": { blockType: "featureList", adapt: adapt079, View: View079 },
  "shadcnui-blocks.features-17": { blockType: "featureList", adapt: adapt080, View: View080 },
  "shadcnui-blocks.features-18": { blockType: "featureList", adapt: adapt081, View: View081 },
  "shadcnui-blocks.faq-08": { blockType: "faq", adapt: adapt082, View: View082 },
  "shadcnui-blocks.faq-09": { blockType: "faq", adapt: adapt083, View: View083 },
  "shadcnui-blocks.faq-10": { blockType: "faq", adapt: adapt084, View: View084 },
  "shadcnui-blocks.faq-11": { blockType: "faq", adapt: adapt085, View: View085 },
  "shadcnui-blocks.faq-12": { blockType: "faq", adapt: adapt086, View: View086 },
  "shadcnui-blocks.faq-13": { blockType: "faq", adapt: adapt087, View: View087 },
  "shadcnui-blocks.faq-14": { blockType: "faq", adapt: adapt088, View: View088 },
  "shadcnui-blocks.logo-cloud-08": { blockType: "logoCloud", adapt: adapt089, View: View089 },
  "shadcnui-blocks.logo-cloud-09": { blockType: "logoCloud", adapt: adapt090, View: View090 },
  "shadcnui-blocks.logo-cloud-10": { blockType: "logoCloud", adapt: adapt091, View: View091 },
  "shadcnui-blocks.logo-cloud-11": { blockType: "logoCloud", adapt: adapt092, View: View092 },
  "shadcnui-blocks.logo-cloud-12": { blockType: "logoCloud", adapt: adapt093, View: View093 },
  "shadcnui-blocks.logo-cloud-13": { blockType: "logoCloud", adapt: adapt094, View: View094 },
  "shadcnui-blocks.logo-cloud-14": { blockType: "logoCloud", adapt: adapt095, View: View095 },
  "shadcnui-blocks.logo-cloud-15": { blockType: "logoCloud", adapt: adapt096, View: View096 },
  "shadcnui-blocks.pricing-07": { blockType: "pricing", adapt: adapt097, View: View097 },
  "shadcnui-blocks.pricing-08": { blockType: "pricing", adapt: adapt098, View: View098 },
  "shadcnui-blocks.pricing-09": { blockType: "pricing", adapt: adapt099, View: View099 },
  "shadcnui-blocks.pricing-10": { blockType: "pricing", adapt: adapt100, View: View100 },
  "shadcnui-blocks.stats-03": { blockType: "stats", adapt: adapt101, View: View101 },
  "shadcnui-blocks.stats-04": { blockType: "stats", adapt: adapt102, View: View102 },
  "shadcnui-blocks.stats-05": { blockType: "stats", adapt: adapt103, View: View103 },
  "shadcnui-blocks.stats-06": { blockType: "stats", adapt: adapt104, View: View104 },
  "shadcnui-blocks.stats-07": { blockType: "stats", adapt: adapt105, View: View105 },
  "shadcnui-blocks.stats-08": { blockType: "stats", adapt: adapt106, View: View106 },
  "shadcnui-blocks.stats-09": { blockType: "stats", adapt: adapt107, View: View107 },
  "shadcnui-blocks.stats-10": { blockType: "stats", adapt: adapt108, View: View108 },
  "shadcnui-blocks.stats-11": { blockType: "stats", adapt: adapt109, View: View109 },
  "shadcnui-blocks.team-06": { blockType: "team", adapt: adapt110, View: View110 },
  "shadcnui-blocks.team-07": { blockType: "team", adapt: adapt111, View: View111 },
  "shadcnui-blocks.team-08": { blockType: "team", adapt: adapt112, View: View112 },
  "shadcnui-blocks.team-09": { blockType: "team", adapt: adapt113, View: View113 },
  "shadcnui-blocks.team-10": { blockType: "team", adapt: adapt114, View: View114 },
  "shadcnui-blocks.team-11": { blockType: "team", adapt: adapt115, View: View115 },
  "shadcnui-blocks.team-12": { blockType: "team", adapt: adapt116, View: View116 },
  "shadcnui-blocks.team-13": { blockType: "team", adapt: adapt117, View: View117 },
  "shadcnui-blocks.testimonials-07": { blockType: "testimonials", adapt: adapt118, View: View118 },
  "shadcnui-blocks.testimonials-08": { blockType: "testimonials", adapt: adapt119, View: View119 },
  "shadcnui-blocks.testimonials-09": { blockType: "testimonials", adapt: adapt120, View: View120 },
  "shadcnui-blocks.testimonials-10": { blockType: "testimonials", adapt: adapt121, View: View121 },
  "shadcnui-blocks.testimonials-11": { blockType: "testimonials", adapt: adapt122, View: View122 },
  "shadcnui-blocks.testimonials-12": { blockType: "testimonials", adapt: adapt123, View: View123 },
  "shadcnui-blocks.testimonials-13": { blockType: "testimonials", adapt: adapt124, View: View124 },
  "shadcnui-blocks.blog-04": { blockType: "blogCards", adapt: adapt125, View: View125 },
  "shadcnui-blocks.blog-05": { blockType: "blogCards", adapt: adapt126, View: View126 },
  "shadcnui-blocks.blog-06": { blockType: "blogCards", adapt: adapt127, View: View127 },
  "shadcnui-blocks.integrations-01": { blockType: "logoCloud", adapt: adapt128, View: View128 },
  "shadcnui-blocks.integrations-02": { blockType: "logoCloud", adapt: adapt129, View: View129 },
  "shadcnui-blocks.integrations-03": { blockType: "logoCloud", adapt: adapt130, View: View130 },
  "shadcnui-blocks.integrations-04": { blockType: "logoCloud", adapt: adapt131, View: View131 },
  "shadcnui-blocks.integrations-05": { blockType: "logoCloud", adapt: adapt132, View: View132 },
} as const
export function ShadcnUiExplicitBlockView({ block, options, variant }: { block: Block; options: BlockRenderOptions; variant: string }) {
  const definition = definitions[variant as keyof typeof definitions]
  if (!definition || definition.blockType !== block.blockType) throw new Error(`Unresolved provider block variant "${variant}" for block type "${block.blockType}".`)
  const model = (definition.adapt as (input: { block: Block; options: BlockRenderOptions }) => { block: Block; options: BlockRenderOptions })({ block, options })
  const { View } = definition
  return <View model={model} />
}
