// Generated by scripts/import-shadcnui-blocks.mjs. Do not edit by hand.
import * as React from "react"
import type { Block } from "@siteinabox/contracts"
import type { BlockRenderOptions } from "../../blocks/types"
import View001 from "./variants/blog-01/view"
import View002 from "./variants/blog-02/view"
import View003 from "./variants/blog-03/view"
import View004 from "./variants/contact-01/view"
import View005 from "./variants/contact-02/view"
import View006 from "./variants/contact-03/view"
import View007 from "./variants/faq-01/view"
import View008 from "./variants/faq-02/view"
import View009 from "./variants/faq-03/view"
import View010 from "./variants/faq-04/view"
import View011 from "./variants/faq-05/view"
import View012 from "./variants/faq-06/view"
import View013 from "./variants/faq-07/view"
import View014 from "./variants/features-01/view"
import View015 from "./variants/features-02/view"
import View016 from "./variants/features-03/view"
import View017 from "./variants/features-04/view"
import View018 from "./variants/features-05/view"
import View019 from "./variants/features-06/view"
import View020 from "./variants/features-07/view"
import View021 from "./variants/hero-01/view"
import View022 from "./variants/hero-02/view"
import View023 from "./variants/hero-03/view"
import View024 from "./variants/hero-04/view"
import View025 from "./variants/hero-05/view"
import View026 from "./variants/hero-06/view"
import View027 from "./variants/hero-07/view"
import View028 from "./variants/logo-cloud-01/view"
import View029 from "./variants/logo-cloud-02/view"
import View030 from "./variants/logo-cloud-03/view"
import View031 from "./variants/logo-cloud-04/view"
import View032 from "./variants/logo-cloud-05/view"
import View033 from "./variants/logo-cloud-06/view"
import View034 from "./variants/logo-cloud-07/view"
import View035 from "./variants/pricing-01/view"
import View036 from "./variants/pricing-02/view"
import View037 from "./variants/pricing-03/view"
import View038 from "./variants/pricing-04/view"
import View039 from "./variants/pricing-05/view"
import View040 from "./variants/pricing-06/view"
import View041 from "./variants/stats-01/view"
import View042 from "./variants/stats-02/view"
import View043 from "./variants/team-01/view"
import View044 from "./variants/team-02/view"
import View045 from "./variants/team-03/view"
import View046 from "./variants/team-04/view"
import View047 from "./variants/team-05/view"
import View048 from "./variants/testimonials-01/view"
import View049 from "./variants/testimonials-02/view"
import View050 from "./variants/testimonials-03/view"
import View051 from "./variants/testimonials-04/view"
import View052 from "./variants/testimonials-05/view"
import View053 from "./variants/testimonials-06/view"
import View054 from "./variants/timeline-01/view"
import View055 from "./variants/timeline-02/view"
import View056 from "./variants/timeline-03/view"
import View057 from "./variants/timeline-04/view"
import View058 from "./variants/timeline-05/view"
import View059 from "./variants/timeline-06/view"
import View060 from "./variants/timeline-07/view"
import View061 from "./variants/cta-01/view"
import View062 from "./variants/cta-02/view"
import View063 from "./variants/cta-03/view"
import View064 from "./variants/cta-04/view"
import View065 from "./variants/cta-05/view"
import View066 from "./variants/cta-06/view"
import View067 from "./variants/cta-07/view"
import View068 from "./variants/carousel-block-01/view"
import View069 from "./variants/carousel-block-02/view"
import View070 from "./variants/hero-08/view"
import View071 from "./variants/features-08/view"
import View072 from "./variants/features-09/view"
import View073 from "./variants/features-10/view"
import View074 from "./variants/features-11/view"
import View075 from "./variants/features-12/view"
import View076 from "./variants/features-13/view"
import View077 from "./variants/features-14/view"
import View078 from "./variants/features-15/view"
import View079 from "./variants/features-16/view"
import View080 from "./variants/features-17/view"
import View081 from "./variants/features-18/view"
import View082 from "./variants/faq-08/view"
import View083 from "./variants/faq-09/view"
import View084 from "./variants/faq-10/view"
import View085 from "./variants/faq-11/view"
import View086 from "./variants/faq-12/view"
import View087 from "./variants/faq-13/view"
import View088 from "./variants/faq-14/view"
import View089 from "./variants/logo-cloud-08/view"
import View090 from "./variants/logo-cloud-09/view"
import View091 from "./variants/logo-cloud-10/view"
import View092 from "./variants/logo-cloud-11/view"
import View093 from "./variants/logo-cloud-12/view"
import View094 from "./variants/logo-cloud-13/view"
import View095 from "./variants/logo-cloud-14/view"
import View096 from "./variants/logo-cloud-15/view"
import View097 from "./variants/pricing-07/view"
import View098 from "./variants/pricing-08/view"
import View099 from "./variants/pricing-09/view"
import View100 from "./variants/pricing-10/view"
import View101 from "./variants/stats-03/view"
import View102 from "./variants/stats-04/view"
import View103 from "./variants/stats-05/view"
import View104 from "./variants/stats-06/view"
import View105 from "./variants/stats-07/view"
import View106 from "./variants/stats-08/view"
import View107 from "./variants/stats-09/view"
import View108 from "./variants/stats-10/view"
import View109 from "./variants/stats-11/view"
import View110 from "./variants/team-06/view"
import View111 from "./variants/team-07/view"
import View112 from "./variants/team-08/view"
import View113 from "./variants/team-09/view"
import View114 from "./variants/team-10/view"
import View115 from "./variants/team-11/view"
import View116 from "./variants/team-12/view"
import View117 from "./variants/team-13/view"
import View118 from "./variants/testimonials-07/view"
import View119 from "./variants/testimonials-08/view"
import View120 from "./variants/testimonials-09/view"
import View121 from "./variants/testimonials-10/view"
import View122 from "./variants/testimonials-11/view"
import View123 from "./variants/testimonials-12/view"
import View124 from "./variants/testimonials-13/view"
import View125 from "./variants/blog-04/view"
import View126 from "./variants/blog-05/view"
import View127 from "./variants/blog-06/view"
import View128 from "./variants/integrations-01/view"
import View129 from "./variants/integrations-02/view"
import View130 from "./variants/integrations-03/view"
import View131 from "./variants/integrations-04/view"
import View132 from "./variants/integrations-05/view"
const definitions = {
  "shadcnui-blocks.blog-01": { blockType: "blogCards", View: View001 },
  "shadcnui-blocks.blog-02": { blockType: "blogCards", View: View002 },
  "shadcnui-blocks.blog-03": { blockType: "blogCards", View: View003 },
  "shadcnui-blocks.contact-01": { blockType: "contactDetails", View: View004 },
  "shadcnui-blocks.contact-02": { blockType: "contactSection", View: View005 },
  "shadcnui-blocks.contact-03": { blockType: "contactDetails", View: View006 },
  "shadcnui-blocks.faq-01": { blockType: "faq", View: View007 },
  "shadcnui-blocks.faq-02": { blockType: "faq", View: View008 },
  "shadcnui-blocks.faq-03": { blockType: "faq", View: View009 },
  "shadcnui-blocks.faq-04": { blockType: "faq", View: View010 },
  "shadcnui-blocks.faq-05": { blockType: "faq", View: View011 },
  "shadcnui-blocks.faq-06": { blockType: "faq", View: View012 },
  "shadcnui-blocks.faq-07": { blockType: "faq", View: View013 },
  "shadcnui-blocks.features-01": { blockType: "featureList", View: View014 },
  "shadcnui-blocks.features-02": { blockType: "featureList", View: View015 },
  "shadcnui-blocks.features-03": { blockType: "featureList", View: View016 },
  "shadcnui-blocks.features-04": { blockType: "featureList", View: View017 },
  "shadcnui-blocks.features-05": { blockType: "featureList", View: View018 },
  "shadcnui-blocks.features-06": { blockType: "featureList", View: View019 },
  "shadcnui-blocks.features-07": { blockType: "featureList", View: View020 },
  "shadcnui-blocks.hero-01": { blockType: "hero", View: View021 },
  "shadcnui-blocks.hero-02": { blockType: "hero", View: View022 },
  "shadcnui-blocks.hero-03": { blockType: "hero", View: View023 },
  "shadcnui-blocks.hero-04": { blockType: "hero", View: View024 },
  "shadcnui-blocks.hero-05": { blockType: "hero", View: View025 },
  "shadcnui-blocks.hero-06": { blockType: "hero", View: View026 },
  "shadcnui-blocks.hero-07": { blockType: "hero", View: View027 },
  "shadcnui-blocks.logo-cloud-01": { blockType: "logoCloud", View: View028 },
  "shadcnui-blocks.logo-cloud-02": { blockType: "logoCloud", View: View029 },
  "shadcnui-blocks.logo-cloud-03": { blockType: "logoCloud", View: View030 },
  "shadcnui-blocks.logo-cloud-04": { blockType: "logoCloud", View: View031 },
  "shadcnui-blocks.logo-cloud-05": { blockType: "logoCloud", View: View032 },
  "shadcnui-blocks.logo-cloud-06": { blockType: "logoCloud", View: View033 },
  "shadcnui-blocks.logo-cloud-07": { blockType: "logoCloud", View: View034 },
  "shadcnui-blocks.pricing-01": { blockType: "pricing", View: View035 },
  "shadcnui-blocks.pricing-02": { blockType: "pricing", View: View036 },
  "shadcnui-blocks.pricing-03": { blockType: "pricing", View: View037 },
  "shadcnui-blocks.pricing-04": { blockType: "pricing", View: View038 },
  "shadcnui-blocks.pricing-05": { blockType: "pricing", View: View039 },
  "shadcnui-blocks.pricing-06": { blockType: "pricing", View: View040 },
  "shadcnui-blocks.stats-01": { blockType: "stats", View: View041 },
  "shadcnui-blocks.stats-02": { blockType: "stats", View: View042 },
  "shadcnui-blocks.team-01": { blockType: "team", View: View043 },
  "shadcnui-blocks.team-02": { blockType: "team", View: View044 },
  "shadcnui-blocks.team-03": { blockType: "team", View: View045 },
  "shadcnui-blocks.team-04": { blockType: "team", View: View046 },
  "shadcnui-blocks.team-05": { blockType: "team", View: View047 },
  "shadcnui-blocks.testimonials-01": { blockType: "testimonials", View: View048 },
  "shadcnui-blocks.testimonials-02": { blockType: "testimonials", View: View049 },
  "shadcnui-blocks.testimonials-03": { blockType: "testimonials", View: View050 },
  "shadcnui-blocks.testimonials-04": { blockType: "testimonials", View: View051 },
  "shadcnui-blocks.testimonials-05": { blockType: "testimonials", View: View052 },
  "shadcnui-blocks.testimonials-06": { blockType: "testimonials", View: View053 },
  "shadcnui-blocks.timeline-01": { blockType: "timeline", View: View054 },
  "shadcnui-blocks.timeline-02": { blockType: "timeline", View: View055 },
  "shadcnui-blocks.timeline-03": { blockType: "timeline", View: View056 },
  "shadcnui-blocks.timeline-04": { blockType: "timeline", View: View057 },
  "shadcnui-blocks.timeline-05": { blockType: "timeline", View: View058 },
  "shadcnui-blocks.timeline-06": { blockType: "timeline", View: View059 },
  "shadcnui-blocks.timeline-07": { blockType: "timeline", View: View060 },
  "shadcnui-blocks.cta-01": { blockType: "cta", View: View061 },
  "shadcnui-blocks.cta-02": { blockType: "cta", View: View062 },
  "shadcnui-blocks.cta-03": { blockType: "cta", View: View063 },
  "shadcnui-blocks.cta-04": { blockType: "cta", View: View064 },
  "shadcnui-blocks.cta-05": { blockType: "cta", View: View065 },
  "shadcnui-blocks.cta-06": { blockType: "cta", View: View066 },
  "shadcnui-blocks.cta-07": { blockType: "cta", View: View067 },
  "shadcnui-blocks.carousel-block-01": { blockType: "gallery", View: View068 },
  "shadcnui-blocks.carousel-block-02": { blockType: "gallery", View: View069 },
  "shadcnui-blocks.hero-08": { blockType: "hero", View: View070 },
  "shadcnui-blocks.features-08": { blockType: "featureList", View: View071 },
  "shadcnui-blocks.features-09": { blockType: "featureList", View: View072 },
  "shadcnui-blocks.features-10": { blockType: "featureList", View: View073 },
  "shadcnui-blocks.features-11": { blockType: "featureList", View: View074 },
  "shadcnui-blocks.features-12": { blockType: "featureList", View: View075 },
  "shadcnui-blocks.features-13": { blockType: "featureList", View: View076 },
  "shadcnui-blocks.features-14": { blockType: "featureList", View: View077 },
  "shadcnui-blocks.features-15": { blockType: "featureList", View: View078 },
  "shadcnui-blocks.features-16": { blockType: "featureList", View: View079 },
  "shadcnui-blocks.features-17": { blockType: "featureList", View: View080 },
  "shadcnui-blocks.features-18": { blockType: "featureList", View: View081 },
  "shadcnui-blocks.faq-08": { blockType: "faq", View: View082 },
  "shadcnui-blocks.faq-09": { blockType: "faq", View: View083 },
  "shadcnui-blocks.faq-10": { blockType: "faq", View: View084 },
  "shadcnui-blocks.faq-11": { blockType: "faq", View: View085 },
  "shadcnui-blocks.faq-12": { blockType: "faq", View: View086 },
  "shadcnui-blocks.faq-13": { blockType: "faq", View: View087 },
  "shadcnui-blocks.faq-14": { blockType: "faq", View: View088 },
  "shadcnui-blocks.logo-cloud-08": { blockType: "logoCloud", View: View089 },
  "shadcnui-blocks.logo-cloud-09": { blockType: "logoCloud", View: View090 },
  "shadcnui-blocks.logo-cloud-10": { blockType: "logoCloud", View: View091 },
  "shadcnui-blocks.logo-cloud-11": { blockType: "logoCloud", View: View092 },
  "shadcnui-blocks.logo-cloud-12": { blockType: "logoCloud", View: View093 },
  "shadcnui-blocks.logo-cloud-13": { blockType: "logoCloud", View: View094 },
  "shadcnui-blocks.logo-cloud-14": { blockType: "logoCloud", View: View095 },
  "shadcnui-blocks.logo-cloud-15": { blockType: "logoCloud", View: View096 },
  "shadcnui-blocks.pricing-07": { blockType: "pricing", View: View097 },
  "shadcnui-blocks.pricing-08": { blockType: "pricing", View: View098 },
  "shadcnui-blocks.pricing-09": { blockType: "pricing", View: View099 },
  "shadcnui-blocks.pricing-10": { blockType: "pricing", View: View100 },
  "shadcnui-blocks.stats-03": { blockType: "stats", View: View101 },
  "shadcnui-blocks.stats-04": { blockType: "stats", View: View102 },
  "shadcnui-blocks.stats-05": { blockType: "stats", View: View103 },
  "shadcnui-blocks.stats-06": { blockType: "stats", View: View104 },
  "shadcnui-blocks.stats-07": { blockType: "stats", View: View105 },
  "shadcnui-blocks.stats-08": { blockType: "stats", View: View106 },
  "shadcnui-blocks.stats-09": { blockType: "stats", View: View107 },
  "shadcnui-blocks.stats-10": { blockType: "stats", View: View108 },
  "shadcnui-blocks.stats-11": { blockType: "stats", View: View109 },
  "shadcnui-blocks.team-06": { blockType: "team", View: View110 },
  "shadcnui-blocks.team-07": { blockType: "team", View: View111 },
  "shadcnui-blocks.team-08": { blockType: "team", View: View112 },
  "shadcnui-blocks.team-09": { blockType: "team", View: View113 },
  "shadcnui-blocks.team-10": { blockType: "team", View: View114 },
  "shadcnui-blocks.team-11": { blockType: "team", View: View115 },
  "shadcnui-blocks.team-12": { blockType: "team", View: View116 },
  "shadcnui-blocks.team-13": { blockType: "team", View: View117 },
  "shadcnui-blocks.testimonials-07": { blockType: "testimonials", View: View118 },
  "shadcnui-blocks.testimonials-08": { blockType: "testimonials", View: View119 },
  "shadcnui-blocks.testimonials-09": { blockType: "testimonials", View: View120 },
  "shadcnui-blocks.testimonials-10": { blockType: "testimonials", View: View121 },
  "shadcnui-blocks.testimonials-11": { blockType: "testimonials", View: View122 },
  "shadcnui-blocks.testimonials-12": { blockType: "testimonials", View: View123 },
  "shadcnui-blocks.testimonials-13": { blockType: "testimonials", View: View124 },
  "shadcnui-blocks.blog-04": { blockType: "blogCards", View: View125 },
  "shadcnui-blocks.blog-05": { blockType: "blogCards", View: View126 },
  "shadcnui-blocks.blog-06": { blockType: "blogCards", View: View127 },
  "shadcnui-blocks.integrations-01": { blockType: "logoCloud", View: View128 },
  "shadcnui-blocks.integrations-02": { blockType: "logoCloud", View: View129 },
  "shadcnui-blocks.integrations-03": { blockType: "logoCloud", View: View130 },
  "shadcnui-blocks.integrations-04": { blockType: "logoCloud", View: View131 },
  "shadcnui-blocks.integrations-05": { blockType: "logoCloud", View: View132 },
} as const
export function ShadcnUiExplicitBlockView({ block, options, variant }: { block: Block; options: BlockRenderOptions; variant: string }) {
  const definition = definitions[variant as keyof typeof definitions]
  if (!definition || definition.blockType !== block.blockType) throw new Error(`Unresolved provider block variant "${variant}" for block type "${block.blockType}".`)
  const { View } = definition
  return <View block={block as never} options={options} />
}
