// Generated by scripts/import-shadcnui-blocks.mjs. Do not edit by hand.
import * as React from "react"
import { TooltipProvider } from "@siteinabox/ui/providers/shadcnui-blocks/radix-nova"
import { LiteralProviderReferenceView } from "./runtime/literal-view"
import Literal001 from "./variants/blog-01/literal"
import Literal002 from "./variants/blog-02/literal"
import Literal003 from "./variants/blog-03/literal"
import Literal004 from "./variants/contact-01/literal"
import Literal005 from "./variants/contact-02/literal"
import Literal006 from "./variants/contact-03/literal"
import Literal007 from "./variants/faq-01/literal"
import Literal008 from "./variants/faq-02/literal"
import Literal009 from "./variants/faq-03/literal"
import Literal010 from "./variants/faq-04/literal"
import Literal011 from "./variants/faq-05/literal"
import Literal012 from "./variants/faq-06/literal"
import Literal013 from "./variants/faq-07/literal"
import Literal014 from "./variants/features-01/literal"
import Literal015 from "./variants/features-02/literal"
import Literal016 from "./variants/features-03/literal"
import Literal017 from "./variants/features-04/literal"
import Literal018 from "./variants/features-05/literal"
import Literal019 from "./variants/features-06/literal"
import Literal020 from "./variants/features-07/literal"
import Literal021 from "./variants/footer-01/literal"
import Literal022 from "./variants/footer-02/literal"
import Literal023 from "./variants/footer-03/literal"
import Literal024 from "./variants/footer-04/literal"
import Literal025 from "./variants/footer-05/literal"
import Literal026 from "./variants/hero-01/literal"
import Literal027 from "./variants/hero-02/literal"
import Literal028 from "./variants/hero-03/literal"
import Literal029 from "./variants/hero-04/literal"
import Literal030 from "./variants/hero-05/literal"
import Literal031 from "./variants/hero-06/literal"
import Literal032 from "./variants/hero-07/literal"
import Literal033 from "./variants/logo-cloud-01/literal"
import Literal034 from "./variants/logo-cloud-02/literal"
import Literal035 from "./variants/logo-cloud-03/literal"
import Literal036 from "./variants/logo-cloud-04/literal"
import Literal037 from "./variants/logo-cloud-05/literal"
import Literal038 from "./variants/logo-cloud-06/literal"
import Literal039 from "./variants/logo-cloud-07/literal"
import Literal040 from "./variants/navbar-01/literal"
import Literal041 from "./variants/navbar-02/literal"
import Literal042 from "./variants/navbar-03/literal"
import Literal043 from "./variants/navbar-04/literal"
import Literal044 from "./variants/navbar-05/literal"
import Literal045 from "./variants/pricing-01/literal"
import Literal046 from "./variants/pricing-02/literal"
import Literal047 from "./variants/pricing-03/literal"
import Literal048 from "./variants/pricing-04/literal"
import Literal049 from "./variants/pricing-05/literal"
import Literal050 from "./variants/pricing-06/literal"
import Literal051 from "./variants/stats-01/literal"
import Literal052 from "./variants/stats-02/literal"
import Literal053 from "./variants/team-01/literal"
import Literal054 from "./variants/team-02/literal"
import Literal055 from "./variants/team-03/literal"
import Literal056 from "./variants/team-04/literal"
import Literal057 from "./variants/team-05/literal"
import Literal058 from "./variants/testimonials-01/literal"
import Literal059 from "./variants/testimonials-02/literal"
import Literal060 from "./variants/testimonials-03/literal"
import Literal061 from "./variants/testimonials-04/literal"
import Literal062 from "./variants/testimonials-05/literal"
import Literal063 from "./variants/testimonials-06/literal"
import Literal064 from "./variants/timeline-01/literal"
import Literal065 from "./variants/timeline-02/literal"
import Literal066 from "./variants/timeline-03/literal"
import Literal067 from "./variants/timeline-04/literal"
import Literal068 from "./variants/timeline-05/literal"
import Literal069 from "./variants/timeline-06/literal"
import Literal070 from "./variants/timeline-07/literal"
import Literal071 from "./variants/banner-01/literal"
import Literal072 from "./variants/banner-02/literal"
import Literal073 from "./variants/banner-03/literal"
import Literal074 from "./variants/banner-04/literal"
import Literal075 from "./variants/cta-01/literal"
import Literal076 from "./variants/cta-02/literal"
import Literal077 from "./variants/cta-03/literal"
import Literal078 from "./variants/cta-04/literal"
import Literal079 from "./variants/cta-05/literal"
import Literal080 from "./variants/cta-06/literal"
import Literal081 from "./variants/cta-07/literal"
import Literal082 from "./variants/carousel-block-01/literal"
import Literal083 from "./variants/carousel-block-02/literal"
import Literal084 from "./variants/hero-08/literal"
import Literal085 from "./variants/features-08/literal"
import Literal086 from "./variants/features-09/literal"
import Literal087 from "./variants/features-10/literal"
import Literal088 from "./variants/features-11/literal"
import Literal089 from "./variants/features-12/literal"
import Literal090 from "./variants/features-13/literal"
import Literal091 from "./variants/features-14/literal"
import Literal092 from "./variants/features-15/literal"
import Literal093 from "./variants/features-16/literal"
import Literal094 from "./variants/features-17/literal"
import Literal095 from "./variants/features-18/literal"
import Literal096 from "./variants/faq-08/literal"
import Literal097 from "./variants/faq-09/literal"
import Literal098 from "./variants/faq-10/literal"
import Literal099 from "./variants/faq-11/literal"
import Literal100 from "./variants/faq-12/literal"
import Literal101 from "./variants/faq-13/literal"
import Literal102 from "./variants/faq-14/literal"
import Literal103 from "./variants/footer-06/literal"
import Literal104 from "./variants/footer-07/literal"
import Literal105 from "./variants/logo-cloud-08/literal"
import Literal106 from "./variants/logo-cloud-09/literal"
import Literal107 from "./variants/logo-cloud-10/literal"
import Literal108 from "./variants/logo-cloud-11/literal"
import Literal109 from "./variants/logo-cloud-12/literal"
import Literal110 from "./variants/logo-cloud-13/literal"
import Literal111 from "./variants/logo-cloud-14/literal"
import Literal112 from "./variants/logo-cloud-15/literal"
import Literal113 from "./variants/pricing-07/literal"
import Literal114 from "./variants/pricing-08/literal"
import Literal115 from "./variants/pricing-09/literal"
import Literal116 from "./variants/pricing-10/literal"
import Literal117 from "./variants/stats-03/literal"
import Literal118 from "./variants/stats-04/literal"
import Literal119 from "./variants/stats-05/literal"
import Literal120 from "./variants/stats-06/literal"
import Literal121 from "./variants/stats-07/literal"
import Literal122 from "./variants/stats-08/literal"
import Literal123 from "./variants/stats-09/literal"
import Literal124 from "./variants/stats-10/literal"
import Literal125 from "./variants/stats-11/literal"
import Literal126 from "./variants/team-06/literal"
import Literal127 from "./variants/team-07/literal"
import Literal128 from "./variants/team-08/literal"
import Literal129 from "./variants/team-09/literal"
import Literal130 from "./variants/team-10/literal"
import Literal131 from "./variants/team-11/literal"
import Literal132 from "./variants/team-12/literal"
import Literal133 from "./variants/team-13/literal"
import Literal134 from "./variants/testimonials-07/literal"
import Literal135 from "./variants/testimonials-08/literal"
import Literal136 from "./variants/testimonials-09/literal"
import Literal137 from "./variants/testimonials-10/literal"
import Literal138 from "./variants/testimonials-11/literal"
import Literal139 from "./variants/testimonials-12/literal"
import Literal140 from "./variants/testimonials-13/literal"
import Literal141 from "./variants/blog-04/literal"
import Literal142 from "./variants/blog-05/literal"
import Literal143 from "./variants/blog-06/literal"
import Literal144 from "./variants/not-found-01/literal"
import Literal145 from "./variants/not-found-02/literal"
import Literal146 from "./variants/not-found-03/literal"
import Literal147 from "./variants/not-found-04/literal"
import Literal148 from "./variants/not-found-05/literal"
import Literal149 from "./variants/not-found-06/literal"
import Literal150 from "./variants/not-found-07/literal"
import Literal151 from "./variants/not-found-08/literal"
import Literal152 from "./variants/integrations-01/literal"
import Literal153 from "./variants/integrations-02/literal"
import Literal154 from "./variants/integrations-03/literal"
import Literal155 from "./variants/integrations-04/literal"
import Literal156 from "./variants/integrations-05/literal"
const literals = {
  "shadcnui-blocks.blog-01": Literal001,
  "shadcnui-blocks.blog-02": Literal002,
  "shadcnui-blocks.blog-03": Literal003,
  "shadcnui-blocks.contact-01": Literal004,
  "shadcnui-blocks.contact-02": Literal005,
  "shadcnui-blocks.contact-03": Literal006,
  "shadcnui-blocks.faq-01": Literal007,
  "shadcnui-blocks.faq-02": Literal008,
  "shadcnui-blocks.faq-03": Literal009,
  "shadcnui-blocks.faq-04": Literal010,
  "shadcnui-blocks.faq-05": Literal011,
  "shadcnui-blocks.faq-06": Literal012,
  "shadcnui-blocks.faq-07": Literal013,
  "shadcnui-blocks.features-01": Literal014,
  "shadcnui-blocks.features-02": Literal015,
  "shadcnui-blocks.features-03": Literal016,
  "shadcnui-blocks.features-04": Literal017,
  "shadcnui-blocks.features-05": Literal018,
  "shadcnui-blocks.features-06": Literal019,
  "shadcnui-blocks.features-07": Literal020,
  "shadcnui-blocks.footer-01": Literal021,
  "shadcnui-blocks.footer-02": Literal022,
  "shadcnui-blocks.footer-03": Literal023,
  "shadcnui-blocks.footer-04": Literal024,
  "shadcnui-blocks.footer-05": Literal025,
  "shadcnui-blocks.hero-01": Literal026,
  "shadcnui-blocks.hero-02": Literal027,
  "shadcnui-blocks.hero-03": Literal028,
  "shadcnui-blocks.hero-04": Literal029,
  "shadcnui-blocks.hero-05": Literal030,
  "shadcnui-blocks.hero-06": Literal031,
  "shadcnui-blocks.hero-07": Literal032,
  "shadcnui-blocks.logo-cloud-01": Literal033,
  "shadcnui-blocks.logo-cloud-02": Literal034,
  "shadcnui-blocks.logo-cloud-03": Literal035,
  "shadcnui-blocks.logo-cloud-04": Literal036,
  "shadcnui-blocks.logo-cloud-05": Literal037,
  "shadcnui-blocks.logo-cloud-06": Literal038,
  "shadcnui-blocks.logo-cloud-07": Literal039,
  "shadcnui-blocks.navbar-01": Literal040,
  "shadcnui-blocks.navbar-02": Literal041,
  "shadcnui-blocks.navbar-03": Literal042,
  "shadcnui-blocks.navbar-04": Literal043,
  "shadcnui-blocks.navbar-05": Literal044,
  "shadcnui-blocks.pricing-01": Literal045,
  "shadcnui-blocks.pricing-02": Literal046,
  "shadcnui-blocks.pricing-03": Literal047,
  "shadcnui-blocks.pricing-04": Literal048,
  "shadcnui-blocks.pricing-05": Literal049,
  "shadcnui-blocks.pricing-06": Literal050,
  "shadcnui-blocks.stats-01": Literal051,
  "shadcnui-blocks.stats-02": Literal052,
  "shadcnui-blocks.team-01": Literal053,
  "shadcnui-blocks.team-02": Literal054,
  "shadcnui-blocks.team-03": Literal055,
  "shadcnui-blocks.team-04": Literal056,
  "shadcnui-blocks.team-05": Literal057,
  "shadcnui-blocks.testimonials-01": Literal058,
  "shadcnui-blocks.testimonials-02": Literal059,
  "shadcnui-blocks.testimonials-03": Literal060,
  "shadcnui-blocks.testimonials-04": Literal061,
  "shadcnui-blocks.testimonials-05": Literal062,
  "shadcnui-blocks.testimonials-06": Literal063,
  "shadcnui-blocks.timeline-01": Literal064,
  "shadcnui-blocks.timeline-02": Literal065,
  "shadcnui-blocks.timeline-03": Literal066,
  "shadcnui-blocks.timeline-04": Literal067,
  "shadcnui-blocks.timeline-05": Literal068,
  "shadcnui-blocks.timeline-06": Literal069,
  "shadcnui-blocks.timeline-07": Literal070,
  "shadcnui-blocks.banner-01": Literal071,
  "shadcnui-blocks.banner-02": Literal072,
  "shadcnui-blocks.banner-03": Literal073,
  "shadcnui-blocks.banner-04": Literal074,
  "shadcnui-blocks.cta-01": Literal075,
  "shadcnui-blocks.cta-02": Literal076,
  "shadcnui-blocks.cta-03": Literal077,
  "shadcnui-blocks.cta-04": Literal078,
  "shadcnui-blocks.cta-05": Literal079,
  "shadcnui-blocks.cta-06": Literal080,
  "shadcnui-blocks.cta-07": Literal081,
  "shadcnui-blocks.carousel-block-01": Literal082,
  "shadcnui-blocks.carousel-block-02": Literal083,
  "shadcnui-blocks.hero-08": Literal084,
  "shadcnui-blocks.features-08": Literal085,
  "shadcnui-blocks.features-09": Literal086,
  "shadcnui-blocks.features-10": Literal087,
  "shadcnui-blocks.features-11": Literal088,
  "shadcnui-blocks.features-12": Literal089,
  "shadcnui-blocks.features-13": Literal090,
  "shadcnui-blocks.features-14": Literal091,
  "shadcnui-blocks.features-15": Literal092,
  "shadcnui-blocks.features-16": Literal093,
  "shadcnui-blocks.features-17": Literal094,
  "shadcnui-blocks.features-18": Literal095,
  "shadcnui-blocks.faq-08": Literal096,
  "shadcnui-blocks.faq-09": Literal097,
  "shadcnui-blocks.faq-10": Literal098,
  "shadcnui-blocks.faq-11": Literal099,
  "shadcnui-blocks.faq-12": Literal100,
  "shadcnui-blocks.faq-13": Literal101,
  "shadcnui-blocks.faq-14": Literal102,
  "shadcnui-blocks.footer-06": Literal103,
  "shadcnui-blocks.footer-07": Literal104,
  "shadcnui-blocks.logo-cloud-08": Literal105,
  "shadcnui-blocks.logo-cloud-09": Literal106,
  "shadcnui-blocks.logo-cloud-10": Literal107,
  "shadcnui-blocks.logo-cloud-11": Literal108,
  "shadcnui-blocks.logo-cloud-12": Literal109,
  "shadcnui-blocks.logo-cloud-13": Literal110,
  "shadcnui-blocks.logo-cloud-14": Literal111,
  "shadcnui-blocks.logo-cloud-15": Literal112,
  "shadcnui-blocks.pricing-07": Literal113,
  "shadcnui-blocks.pricing-08": Literal114,
  "shadcnui-blocks.pricing-09": Literal115,
  "shadcnui-blocks.pricing-10": Literal116,
  "shadcnui-blocks.stats-03": Literal117,
  "shadcnui-blocks.stats-04": Literal118,
  "shadcnui-blocks.stats-05": Literal119,
  "shadcnui-blocks.stats-06": Literal120,
  "shadcnui-blocks.stats-07": Literal121,
  "shadcnui-blocks.stats-08": Literal122,
  "shadcnui-blocks.stats-09": Literal123,
  "shadcnui-blocks.stats-10": Literal124,
  "shadcnui-blocks.stats-11": Literal125,
  "shadcnui-blocks.team-06": Literal126,
  "shadcnui-blocks.team-07": Literal127,
  "shadcnui-blocks.team-08": Literal128,
  "shadcnui-blocks.team-09": Literal129,
  "shadcnui-blocks.team-10": Literal130,
  "shadcnui-blocks.team-11": Literal131,
  "shadcnui-blocks.team-12": Literal132,
  "shadcnui-blocks.team-13": Literal133,
  "shadcnui-blocks.testimonials-07": Literal134,
  "shadcnui-blocks.testimonials-08": Literal135,
  "shadcnui-blocks.testimonials-09": Literal136,
  "shadcnui-blocks.testimonials-10": Literal137,
  "shadcnui-blocks.testimonials-11": Literal138,
  "shadcnui-blocks.testimonials-12": Literal139,
  "shadcnui-blocks.testimonials-13": Literal140,
  "shadcnui-blocks.blog-04": Literal141,
  "shadcnui-blocks.blog-05": Literal142,
  "shadcnui-blocks.blog-06": Literal143,
  "shadcnui-blocks.not-found-01": Literal144,
  "shadcnui-blocks.not-found-02": Literal145,
  "shadcnui-blocks.not-found-03": Literal146,
  "shadcnui-blocks.not-found-04": Literal147,
  "shadcnui-blocks.not-found-05": Literal148,
  "shadcnui-blocks.not-found-06": Literal149,
  "shadcnui-blocks.not-found-07": Literal150,
  "shadcnui-blocks.not-found-08": Literal151,
  "shadcnui-blocks.integrations-01": Literal152,
  "shadcnui-blocks.integrations-02": Literal153,
  "shadcnui-blocks.integrations-03": Literal154,
  "shadcnui-blocks.integrations-04": Literal155,
  "shadcnui-blocks.integrations-05": Literal156,
} as const
export function ShadcnUiPinnedLiteralReference({ adapted, variant }: { adapted: boolean; variant: string }) {
  const Literal = literals[variant as keyof typeof literals]
  if (!Literal) throw new Error(`Unresolved pinned literal provider variant "${variant}".`)
  return adapted ? <LiteralProviderReferenceView Literal={Literal} variant={variant} /> : <TooltipProvider><Literal /></TooltipProvider>
}
