// Generated by scripts/import-shadcnui-blocks.mjs. Do not edit by hand.
import * as React from "react"
import { LiteralProviderReferenceView } from "./runtime/literal-view"
import Literal001 from "./references/blog-01/blog"
import Literal002 from "./references/blog-02/blog"
import Literal003 from "./references/blog-03/blog"
import Literal004 from "./references/contact-01/contact"
import Literal005 from "./references/contact-02/contact"
import Literal006 from "./references/contact-03/contact"
import Literal007 from "./references/faq-01/faq"
import Literal008 from "./references/faq-02/faq"
import Literal009 from "./references/faq-03/faq"
import Literal010 from "./references/faq-04/faq"
import Literal011 from "./references/faq-05/faq"
import Literal012 from "./references/faq-06/faq"
import Literal013 from "./references/faq-07/faq"
import Literal014 from "./references/features-01/features"
import Literal015 from "./references/features-02/features"
import Literal016 from "./references/features-03/features"
import Literal017 from "./references/features-04/features"
import Literal018 from "./references/features-05/features"
import Literal019 from "./references/features-06/features"
import Literal020 from "./references/features-07/features"
import Literal021 from "./references/footer-01/footer"
import Literal022 from "./references/footer-02/footer"
import Literal023 from "./references/footer-03/footer"
import Literal024 from "./references/footer-04/footer"
import Literal025 from "./references/footer-05/footer"
import Literal026 from "./references/hero-01/hero"
import Literal027 from "./references/hero-02/hero"
import Literal028 from "./references/hero-03/hero"
import Literal029 from "./references/hero-04/hero"
import Literal030 from "./references/hero-05/hero"
import Literal031 from "./references/hero-06/hero"
import Literal032 from "./references/hero-07/hero"
import Literal033 from "./references/logo-cloud-01/logo-cloud"
import Literal034 from "./references/logo-cloud-02/logo-cloud"
import Literal035 from "./references/logo-cloud-03/logo-cloud"
import Literal036 from "./references/logo-cloud-04/logo-cloud"
import Literal037 from "./references/logo-cloud-05/logo-cloud"
import Literal038 from "./references/logo-cloud-06/logo-cloud"
import Literal039 from "./references/logo-cloud-07/logo-cloud"
import Literal040 from "./references/navbar-01/navbar"
import Literal041 from "./references/navbar-02/navbar"
import Literal042 from "./references/navbar-03/navbar"
import Literal043 from "./references/navbar-04/navbar"
import Literal044 from "./references/navbar-05/navbar"
import Literal045 from "./references/pricing-01/pricing"
import Literal046 from "./references/pricing-02/pricing"
import Literal047 from "./references/pricing-03/pricing"
import Literal048 from "./references/pricing-04/pricing"
import Literal049 from "./references/pricing-05/pricing"
import Literal050 from "./references/pricing-06/pricing"
import Literal051 from "./references/stats-01/stats"
import Literal052 from "./references/stats-02/stats"
import Literal053 from "./references/team-01/team"
import Literal054 from "./references/team-02/team"
import Literal055 from "./references/team-03/team"
import Literal056 from "./references/team-04/team"
import Literal057 from "./references/team-05/team"
import Literal058 from "./references/testimonials-01/testimonials"
import Literal059 from "./references/testimonials-02/testimonials"
import Literal060 from "./references/testimonials-03/testimonials"
import Literal061 from "./references/testimonials-04/testimonials"
import Literal062 from "./references/testimonials-05/testimonials"
import Literal063 from "./references/testimonials-06/testimonials"
import Literal064 from "./references/timeline-01/timeline"
import Literal065 from "./references/timeline-02/timeline"
import Literal066 from "./references/timeline-03/timeline"
import Literal067 from "./references/timeline-04/timeline"
import Literal068 from "./references/timeline-05/timeline"
import Literal069 from "./references/timeline-06/timeline"
import Literal070 from "./references/timeline-07/timeline"
import Literal071 from "./references/banner-01/banner"
import Literal072 from "./references/banner-02/banner"
import Literal073 from "./references/banner-03/banner"
import Literal074 from "./references/banner-04/banner"
import Literal075 from "./references/cta-01/cta"
import Literal076 from "./references/cta-02/cta"
import Literal077 from "./references/cta-03/cta"
import Literal078 from "./references/cta-04/cta"
import Literal079 from "./references/cta-05/cta"
import Literal080 from "./references/cta-06/cta"
import Literal081 from "./references/cta-07/cta"
import Literal082 from "./references/carousel-block-01/carousel"
import Literal083 from "./references/carousel-block-02/carousel"
import Literal084 from "./references/hero-08/hero"
import Literal085 from "./references/features-08/features"
import Literal086 from "./references/features-09/features"
import Literal087 from "./references/features-10/features"
import Literal088 from "./references/features-11/features"
import Literal089 from "./references/features-12/features"
import Literal090 from "./references/features-13/features"
import Literal091 from "./references/features-14/features"
import Literal092 from "./references/features-15/features"
import Literal093 from "./references/features-16/features"
import Literal094 from "./references/features-17/features"
import Literal095 from "./references/features-18/features"
import Literal096 from "./references/faq-08/faq"
import Literal097 from "./references/faq-09/faq"
import Literal098 from "./references/faq-10/faq"
import Literal099 from "./references/faq-11/faq"
import Literal100 from "./references/faq-12/faq"
import Literal101 from "./references/faq-13/faq"
import Literal102 from "./references/faq-14/faq"
import Literal103 from "./references/footer-06/footer"
import Literal104 from "./references/footer-07/footer"
import Literal105 from "./references/logo-cloud-08/logo-cloud"
import Literal106 from "./references/logo-cloud-09/logo-cloud"
import Literal107 from "./references/logo-cloud-10/logo-cloud"
import Literal108 from "./references/logo-cloud-11/logo-cloud"
import Literal109 from "./references/logo-cloud-12/logo-cloud"
import Literal110 from "./references/logo-cloud-13/logo-cloud"
import Literal111 from "./references/logo-cloud-14/logo-cloud"
import Literal112 from "./references/logo-cloud-15/logo-cloud"
import Literal113 from "./references/pricing-07/pricing"
import Literal114 from "./references/pricing-08/pricing"
import Literal115 from "./references/pricing-09/pricing"
import Literal116 from "./references/pricing-10/pricing"
import Literal117 from "./references/stats-03/stats"
import Literal118 from "./references/stats-04/stats"
import Literal119 from "./references/stats-05/stats"
import Literal120 from "./references/stats-06/stats"
import Literal121 from "./references/stats-07/stats"
import Literal122 from "./references/stats-08/stats"
import Literal123 from "./references/stats-09/stats"
import Literal124 from "./references/stats-10/stats"
import Literal125 from "./references/stats-11/stats"
import Literal126 from "./references/team-06/team"
import Literal127 from "./references/team-07/team"
import Literal128 from "./references/team-08/team"
import Literal129 from "./references/team-09/team"
import Literal130 from "./references/team-10/team"
import Literal131 from "./references/team-11/team"
import Literal132 from "./references/team-12/team"
import Literal133 from "./references/team-13/team"
import Literal134 from "./references/testimonials-07/testimonials"
import Literal135 from "./references/testimonials-08/testimonials"
import Literal136 from "./references/testimonials-09/testimonials"
import Literal137 from "./references/testimonials-10/testimonials"
import Literal138 from "./references/testimonials-11/testimonials"
import Literal139 from "./references/testimonials-12/testimonials"
import Literal140 from "./references/testimonials-13/testimonials"
import Literal141 from "./references/blog-04/blog"
import Literal142 from "./references/blog-05/blog"
import Literal143 from "./references/blog-06/blog"
import Literal144 from "./references/not-found-01/not-found"
import Literal145 from "./references/not-found-02/not-found"
import Literal146 from "./references/not-found-03/not-found"
import Literal147 from "./references/not-found-04/not-found"
import Literal148 from "./references/not-found-05/not-found"
import Literal149 from "./references/not-found-06/not-found"
import Literal150 from "./references/not-found-07/not-found"
import Literal151 from "./references/not-found-08/not-found"
import Literal152 from "./references/integrations-01/integrations"
import Literal153 from "./references/integrations-02/integrations"
import Literal154 from "./references/integrations-03/integrations"
import Literal155 from "./references/integrations-04/integrations"
import Literal156 from "./references/integrations-05/integrations"
const literals = {
  "shadcnui-blocks.blog-01": Literal001,
  "shadcnui-blocks.blog-02": Literal002,
  "shadcnui-blocks.blog-03": Literal003,
  "shadcnui-blocks.contact-01": Literal004,
  "shadcnui-blocks.contact-02": Literal005,
  "shadcnui-blocks.contact-03": Literal006,
  "shadcnui-blocks.faq-01": Literal007,
  "shadcnui-blocks.faq-02": Literal008,
  "shadcnui-blocks.faq-03": Literal009,
  "shadcnui-blocks.faq-04": Literal010,
  "shadcnui-blocks.faq-05": Literal011,
  "shadcnui-blocks.faq-06": Literal012,
  "shadcnui-blocks.faq-07": Literal013,
  "shadcnui-blocks.features-01": Literal014,
  "shadcnui-blocks.features-02": Literal015,
  "shadcnui-blocks.features-03": Literal016,
  "shadcnui-blocks.features-04": Literal017,
  "shadcnui-blocks.features-05": Literal018,
  "shadcnui-blocks.features-06": Literal019,
  "shadcnui-blocks.features-07": Literal020,
  "shadcnui-blocks.footer-01": Literal021,
  "shadcnui-blocks.footer-02": Literal022,
  "shadcnui-blocks.footer-03": Literal023,
  "shadcnui-blocks.footer-04": Literal024,
  "shadcnui-blocks.footer-05": Literal025,
  "shadcnui-blocks.hero-01": Literal026,
  "shadcnui-blocks.hero-02": Literal027,
  "shadcnui-blocks.hero-03": Literal028,
  "shadcnui-blocks.hero-04": Literal029,
  "shadcnui-blocks.hero-05": Literal030,
  "shadcnui-blocks.hero-06": Literal031,
  "shadcnui-blocks.hero-07": Literal032,
  "shadcnui-blocks.logo-cloud-01": Literal033,
  "shadcnui-blocks.logo-cloud-02": Literal034,
  "shadcnui-blocks.logo-cloud-03": Literal035,
  "shadcnui-blocks.logo-cloud-04": Literal036,
  "shadcnui-blocks.logo-cloud-05": Literal037,
  "shadcnui-blocks.logo-cloud-06": Literal038,
  "shadcnui-blocks.logo-cloud-07": Literal039,
  "shadcnui-blocks.navbar-01": Literal040,
  "shadcnui-blocks.navbar-02": Literal041,
  "shadcnui-blocks.navbar-03": Literal042,
  "shadcnui-blocks.navbar-04": Literal043,
  "shadcnui-blocks.navbar-05": Literal044,
  "shadcnui-blocks.pricing-01": Literal045,
  "shadcnui-blocks.pricing-02": Literal046,
  "shadcnui-blocks.pricing-03": Literal047,
  "shadcnui-blocks.pricing-04": Literal048,
  "shadcnui-blocks.pricing-05": Literal049,
  "shadcnui-blocks.pricing-06": Literal050,
  "shadcnui-blocks.stats-01": Literal051,
  "shadcnui-blocks.stats-02": Literal052,
  "shadcnui-blocks.team-01": Literal053,
  "shadcnui-blocks.team-02": Literal054,
  "shadcnui-blocks.team-03": Literal055,
  "shadcnui-blocks.team-04": Literal056,
  "shadcnui-blocks.team-05": Literal057,
  "shadcnui-blocks.testimonials-01": Literal058,
  "shadcnui-blocks.testimonials-02": Literal059,
  "shadcnui-blocks.testimonials-03": Literal060,
  "shadcnui-blocks.testimonials-04": Literal061,
  "shadcnui-blocks.testimonials-05": Literal062,
  "shadcnui-blocks.testimonials-06": Literal063,
  "shadcnui-blocks.timeline-01": Literal064,
  "shadcnui-blocks.timeline-02": Literal065,
  "shadcnui-blocks.timeline-03": Literal066,
  "shadcnui-blocks.timeline-04": Literal067,
  "shadcnui-blocks.timeline-05": Literal068,
  "shadcnui-blocks.timeline-06": Literal069,
  "shadcnui-blocks.timeline-07": Literal070,
  "shadcnui-blocks.banner-01": Literal071,
  "shadcnui-blocks.banner-02": Literal072,
  "shadcnui-blocks.banner-03": Literal073,
  "shadcnui-blocks.banner-04": Literal074,
  "shadcnui-blocks.cta-01": Literal075,
  "shadcnui-blocks.cta-02": Literal076,
  "shadcnui-blocks.cta-03": Literal077,
  "shadcnui-blocks.cta-04": Literal078,
  "shadcnui-blocks.cta-05": Literal079,
  "shadcnui-blocks.cta-06": Literal080,
  "shadcnui-blocks.cta-07": Literal081,
  "shadcnui-blocks.carousel-block-01": Literal082,
  "shadcnui-blocks.carousel-block-02": Literal083,
  "shadcnui-blocks.hero-08": Literal084,
  "shadcnui-blocks.features-08": Literal085,
  "shadcnui-blocks.features-09": Literal086,
  "shadcnui-blocks.features-10": Literal087,
  "shadcnui-blocks.features-11": Literal088,
  "shadcnui-blocks.features-12": Literal089,
  "shadcnui-blocks.features-13": Literal090,
  "shadcnui-blocks.features-14": Literal091,
  "shadcnui-blocks.features-15": Literal092,
  "shadcnui-blocks.features-16": Literal093,
  "shadcnui-blocks.features-17": Literal094,
  "shadcnui-blocks.features-18": Literal095,
  "shadcnui-blocks.faq-08": Literal096,
  "shadcnui-blocks.faq-09": Literal097,
  "shadcnui-blocks.faq-10": Literal098,
  "shadcnui-blocks.faq-11": Literal099,
  "shadcnui-blocks.faq-12": Literal100,
  "shadcnui-blocks.faq-13": Literal101,
  "shadcnui-blocks.faq-14": Literal102,
  "shadcnui-blocks.footer-06": Literal103,
  "shadcnui-blocks.footer-07": Literal104,
  "shadcnui-blocks.logo-cloud-08": Literal105,
  "shadcnui-blocks.logo-cloud-09": Literal106,
  "shadcnui-blocks.logo-cloud-10": Literal107,
  "shadcnui-blocks.logo-cloud-11": Literal108,
  "shadcnui-blocks.logo-cloud-12": Literal109,
  "shadcnui-blocks.logo-cloud-13": Literal110,
  "shadcnui-blocks.logo-cloud-14": Literal111,
  "shadcnui-blocks.logo-cloud-15": Literal112,
  "shadcnui-blocks.pricing-07": Literal113,
  "shadcnui-blocks.pricing-08": Literal114,
  "shadcnui-blocks.pricing-09": Literal115,
  "shadcnui-blocks.pricing-10": Literal116,
  "shadcnui-blocks.stats-03": Literal117,
  "shadcnui-blocks.stats-04": Literal118,
  "shadcnui-blocks.stats-05": Literal119,
  "shadcnui-blocks.stats-06": Literal120,
  "shadcnui-blocks.stats-07": Literal121,
  "shadcnui-blocks.stats-08": Literal122,
  "shadcnui-blocks.stats-09": Literal123,
  "shadcnui-blocks.stats-10": Literal124,
  "shadcnui-blocks.stats-11": Literal125,
  "shadcnui-blocks.team-06": Literal126,
  "shadcnui-blocks.team-07": Literal127,
  "shadcnui-blocks.team-08": Literal128,
  "shadcnui-blocks.team-09": Literal129,
  "shadcnui-blocks.team-10": Literal130,
  "shadcnui-blocks.team-11": Literal131,
  "shadcnui-blocks.team-12": Literal132,
  "shadcnui-blocks.team-13": Literal133,
  "shadcnui-blocks.testimonials-07": Literal134,
  "shadcnui-blocks.testimonials-08": Literal135,
  "shadcnui-blocks.testimonials-09": Literal136,
  "shadcnui-blocks.testimonials-10": Literal137,
  "shadcnui-blocks.testimonials-11": Literal138,
  "shadcnui-blocks.testimonials-12": Literal139,
  "shadcnui-blocks.testimonials-13": Literal140,
  "shadcnui-blocks.blog-04": Literal141,
  "shadcnui-blocks.blog-05": Literal142,
  "shadcnui-blocks.blog-06": Literal143,
  "shadcnui-blocks.not-found-01": Literal144,
  "shadcnui-blocks.not-found-02": Literal145,
  "shadcnui-blocks.not-found-03": Literal146,
  "shadcnui-blocks.not-found-04": Literal147,
  "shadcnui-blocks.not-found-05": Literal148,
  "shadcnui-blocks.not-found-06": Literal149,
  "shadcnui-blocks.not-found-07": Literal150,
  "shadcnui-blocks.not-found-08": Literal151,
  "shadcnui-blocks.integrations-01": Literal152,
  "shadcnui-blocks.integrations-02": Literal153,
  "shadcnui-blocks.integrations-03": Literal154,
  "shadcnui-blocks.integrations-04": Literal155,
  "shadcnui-blocks.integrations-05": Literal156,
} as const
export function ShadcnUiPinnedLiteralReference({ variant }: { variant: string }) {
  const Literal = literals[variant as keyof typeof literals]
  if (!Literal) throw new Error(`Unresolved pinned literal provider variant "${variant}".`)
  return <LiteralProviderReferenceView Literal={Literal} variant={variant} />
}
